DO $$
DECLARE
  cid uuid;
  r1 uuid; r2 uuid; r3 uuid;
  i1 uuid; i2 uuid;
  e1 uuid; e2 uuid;
BEGIN
  SELECT id INTO cid FROM public.companies WHERE name ILIKE 'TitanScale%' ORDER BY created_at LIMIT 1;
  IF cid IS NULL THEN RETURN; END IF;

  ALTER TABLE public.bcm_processes DISABLE TRIGGER bcm_processes_template_lock;
  ALTER TABLE public.bcm_risks DISABLE TRIGGER bcm_risks_template_lock;
  ALTER TABLE public.bcm_assets DISABLE TRIGGER bcm_assets_template_lock;
  ALTER TABLE public.bcm_incidents DISABLE TRIGGER bcm_incidents_template_lock;
  ALTER TABLE public.bcm_exercises DISABLE TRIGGER bcm_exercises_template_lock;
  ALTER TABLE public.bcm_actions DISABLE TRIGGER bcm_actions_template_lock;

  DELETE FROM public.bcm_actions WHERE company_id = cid;
  DELETE FROM public.bcm_exercises WHERE company_id = cid;
  DELETE FROM public.bcm_incidents WHERE company_id = cid;
  DELETE FROM public.bcm_assets WHERE company_id = cid;
  DELETE FROM public.bcm_risks WHERE company_id = cid;
  DELETE FROM public.bcm_processes WHERE company_id = cid;

  INSERT INTO public.bcm_processes
    (company_id, department, process, process_owner, customers_affected, employees_required, equipment_required, it_systems, utilities, materials, critical_suppliers, minimum_operating_level, mtd_hours, rto_hours, rpo_hours, business_impact, quality_regulatory_impact, dependencies, single_point_of_failure, current_backup, criticality, bia_complete, recovery_plan_complete)
  VALUES
    (cid,'Machining','CNC machining of flight-critical brackets','R. Alvarez','Aerospace tier-1 customers (68% of revenue)','6 machinists across 2 shifts','5-axis mill MC-104, mill MC-107','MOM/ERP, CAM server','Electricity, compressed air','7075-T6 aluminium billet','Alpine Metals','3 of 5 spindles running',24,12,NULL,'~$38k per lost day; AOG penalties on two contracts','AS9100 traceability must be maintained; requalification after repair','CAM post-processors, calibrated probes, tooling crib','MC-104 5-axis is the only machine able to run the wing-rib family','Outside processing agreement with Cascade Precision (7-day lead)','critical',true,true),
    (cid,'Assembly','Final assembly and kitting','M. Nguyen','All customers','9 assemblers','Torque systems, test bench','MOM/ERP, e-traveler','Electricity, HVAC','Purchased hardware, fasteners','Northline Fasteners','One line at 60% takt',48,24,NULL,'Shipments stop within 2 days of assembly loss','Torque records are a customer requirement','Machining output, incoming inspection','Single calibrated torque verification bench','Manual torque wrenches with paper log, 5-day limit','critical',true,true),
    (cid,'Quality','Inspection and product release','S. Patel','All customers','3 inspectors','CMM-2, calibrated gauges','Quality module, cert archive','Electricity, HVAC (20±2°C)','Gauge standards','Precision Calibration Inc.','CMM plus manual gauging',24,8,NULL,'No release = no shipments, regardless of production','Release without inspection is a regulatory nonconformance','Temperature-controlled lab, calibration status','CMM-2 is the only machine capable of the profile tolerance','Sub-contract inspection at Cascade Precision','critical',true,false),
    (cid,'IT','ERP / MOM availability','D. Brooks','Indirectly all customers','1 IT lead + MSP','Servers, network','ERP, MOM, file server','Electricity, internet','—','Northstar IT (MSP)','Read-only ERP access',12,8,4,'Scheduling, traceability and shipping all stop','Traceability records must be reconstructable','Internet link, backup integrity','Single fibre link to the site','Cellular failover router; paper travelers for 3 days','critical',true,true),
    (cid,'Supply chain','Raw material supply — aluminium billet','T. Okafor','Aerospace customers','2 planners','—','ERP','—','7075-T6, 6061-T6','Alpine Metals','4 weeks of billet on hand',336,168,NULL,'Production halts once buffer is consumed','Alternate mill requires customer source approval','Mill certs, incoming inspection','Alpine Metals is sole approved mill for 7075-T6','Second source (Ridgeline Alloys) qualified for 6061 only','high',true,false),
    (cid,'Logistics','Shipping and receiving','K. Ferris','All customers','3 warehouse staff','Forklift, dock','ERP, carrier portals','Electricity','Packaging','Regional carrier','Manual pick and paper packing list',48,16,NULL,'Finished goods pile up; revenue recognition slips','Shipping documents are part of the certification package','Dock access, carrier availability','Single loading dock','Second carrier account; local courier for AOG','high',true,true),
    (cid,'Maintenance','Preventive and emergency maintenance','J. Whitfield','Indirect','2 technicians','Tool crib, spares','CMMS module','Electricity','Spare parts','OEM service partners','One technician per shift',72,24,NULL,'Equipment recovery time doubles without maintenance capacity','PM records support AS9100 equipment control','Spares availability, OEM support contracts','Only one technician is trained on the 5-axis controller','Contracted OEM field service, 48h response','high',true,false),
    (cid,'Finance / HR','Payroll and cash management','L. Moreau','—','2 staff','—','Payroll portal, banking','Internet','—','Payroll provider','Manual payroll run',168,72,24,'Employee retention and supplier terms at risk','Statutory filing deadlines','Bank access, payroll provider','Single payroll administrator','Backup administrator at the provider; offline register','medium',false,false);

  INSERT INTO public.bcm_risks
    (company_id, risk, category, department, cause, consequence, affected_process, likelihood, impact, existing_controls, preventive_action, recovery_action, owner_name, due_date, status, residual_risk)
  VALUES
    (cid,'Extended power outage (>8 hours)','utilities','Facilities','Regional grid failure or storm damage','All production stops; in-process parts scrapped; ovens lose cycle','All production',3,4,'Utility contract, surge protection','Quote a generator sized for CMM lab, servers and one cell','Prioritised restart sequence; notify customers within 4 hours','J. Whitfield',current_date + 45,'in_progress','Moderate once generator is installed'),
    (cid,'5-axis mill MC-104 catastrophic spindle failure','equipment','Machining','Bearing wear, crash, or coolant contamination','Wing-rib family cannot be produced in-house; 7-day outside processing lead','CNC machining',3,5,'PM programme, vibration checks, spindle spare on order','Hold a rebuilt spindle on site; monthly vibration trending','Outside processing at Cascade Precision; reprioritise order book','R. Alvarez',current_date + 30,'in_progress','High until the spare spindle arrives'),
    (cid,'Ransomware attack on ERP / file server','technology','IT','Phishing, unpatched remote access','ERP, traceability and scheduling unavailable for days','ERP / MOM availability',3,5,'MFA, EDR, nightly off-site backups','Quarterly phishing tests; immutable backup copies; segment the shop network','Isolate, restore from off-site backup, run paper travelers','D. Brooks',current_date + 21,'open','High — recovery has not been fully tested'),
    (cid,'Alpine Metals (sole-source billet) failure','supply_chain','Supply chain','Financial distress, mill allocation or quality escape','Production halts after the 4-week buffer','Raw material supply',2,5,'4-week buffer stock, quarterly supplier review','Qualify Ridgeline Alloys for 7075-T6 with customer source approval','Release buffer, expedite alternate mill, reprioritise by customer criticality','T. Okafor',current_date + 90,'open','High until the second source is approved'),
    (cid,'Fire in the machining cell','facility','Machining','Chip fire, hydraulic leak, electrical fault','Partial facility loss and extended downtime','CNC machining',2,5,'Suppression on the 5-axis, hot-work permit, monthly inspection','Chip management standard; thermal survey of panels','Emergency response, insurance, alternate facility assessment','J. Whitfield',current_date + 60,'open','Moderate with suppression in place'),
    (cid,'Loss of the only 5-axis programmer','people','Engineering','Resignation, illness or injury','New programmes stall; changeovers slow dramatically','CNC machining',3,4,'Documented post-processors, some programmes archived','Cross-train a second programmer; retain a contract programmer','Contract programmer on 48h call; freeze new programme work','R. Alvarez',current_date + 75,'open','Moderate once cross-training is complete'),
    (cid,'CMM-2 failure or loss of calibration','quality','Quality','Mechanical failure, environmental excursion, calibration lapse','Product cannot be released; shipments stop','Inspection and product release',3,4,'Annual calibration, environmental monitoring','Service contract with 24h response; pre-approve a sub-contract inspection house','Sub-contract inspection; quarantine affected product','S. Patel',current_date + 40,'in_progress','Moderate'),
    (cid,'Compressed air system failure','utilities','Facilities','Compressor failure or dryer fault','Machining and assembly stop within minutes','All production',3,3,'PM on compressor, filters changed quarterly','Hold a rental-compressor agreement; second dryer','Rental compressor within 8 hours; run manual assembly tasks','J. Whitfield',current_date + 30,'open','Low once rental agreement signed'),
    (cid,'Earthquake causing structural damage','facility','Site','Regional seismic event','Facility unavailable; equipment misaligned','All production',2,5,'Seismic anchoring of racking; insurance','Anchor the CMM and mills; annual walkdown','Facility loss plan; alternate facility assessment; customer communication','L. Moreau',current_date + 120,'open','High — inherent'),
    (cid,'Single fibre internet link failure','technology','IT','Cable cut or carrier outage','ERP and customer portals unreachable','ERP / MOM availability',4,3,'Cellular failover router installed','Test failover monthly; document bandwidth limits','Switch to failover; run paper travelers for shipping','D. Brooks',current_date + 14,'mitigated','Low');

  INSERT INTO public.bcm_assets
    (company_id, asset_kind, name, department, process, criticality, has_backup_strategy, recovery_strategy, recovery_time_hours, rpo_hours, last_tested, notes, details)
  VALUES
    (cid,'equipment','MC-104 — 5-axis mill','Machining','Wing-rib machining','critical',true,'Rebuilt spindle on site; outside processing at Cascade Precision if the machine is down more than 72 hours',72,NULL,current_date - 40,'Highest-consequence single asset on site','{"failure_consequence":"Wing-rib family cannot be produced; AOG exposure on two contracts","critical_spares":"Spindle cartridge, drive belts, tool changer arm","spare_location":"Maintenance crib bay 3","service_provider":"Meridian Machine Service","service_contact":"+1 555 0142, 24h","alternate_equipment":"None on site","alternate_process":"Outside processing — Cascade Precision","required_utilities":"480V, compressed air, coolant","required_personnel":"Certified 5-axis operator","last_pm":"2026-07-18","next_pm":"2026-10-18"}'::jsonb),
    (cid,'equipment','MC-107 — 3-axis mill','Machining','Bracket machining','high',true,'Load can be shifted to MC-104 at reduced rate',24,NULL,current_date - 90,NULL,'{"failure_consequence":"Bracket throughput halves","critical_spares":"Ballscrew, servo drive","spare_location":"Maintenance crib bay 2","service_provider":"Meridian Machine Service","alternate_equipment":"MC-104 (reduced rate)","required_personnel":"Machinist"}'::jsonb),
    (cid,'equipment','CMM-2 — coordinate measuring machine','Quality','Product release','critical',true,'24h OEM service contract; sub-contract inspection at Cascade Precision meanwhile',48,NULL,current_date - 25,'Environmental control is part of the recovery requirement','{"failure_consequence":"No product release; shipments stop","critical_spares":"Probe head, stylus set","spare_location":"Quality lab cabinet","service_provider":"Precision Calibration Inc.","service_contact":"+1 555 0188","alternate_process":"Sub-contract inspection","required_utilities":"HVAC 20±2°C","last_pm":"2026-06-02","next_pm":"2026-12-02"}'::jsonb),
    (cid,'equipment','Air compressor + dryer','Facilities','All production','critical',false,'Rental compressor agreement not yet signed',8,NULL,NULL,'Open gap — see the utilities risk','{"failure_consequence":"All pneumatic operations stop within minutes","critical_spares":"Filters, belts","service_provider":"Cascade Air Systems"}'::jsonb),
    (cid,'supplier','Alpine Metals','Supply chain','Raw material supply','critical',false,'4-week buffer; second source not yet approved for 7075-T6',336,NULL,NULL,'Sole approved mill for the primary alloy','{"material_service":"7075-T6 and 6061-T6 aluminium billet","part_number":"RM-7075-*","single_source":"Yes for 7075-T6","alternate_supplier":"Ridgeline Alloys (6061 only)","lead_time":"6 weeks","minimum_inventory":"4 weeks","current_inventory":"4.5 weeks","emergency_contact":"+1 555 0110","transportation_backup":"Expedited LTL","quality_approval":"Yes — customer source approval required"}'::jsonb),
    (cid,'supplier','Northline Fasteners','Supply chain','Assembly hardware','high',true,'Dual sourced with Bolt & Rivet Co.; 6-week safety stock on top movers',168,NULL,current_date - 120,NULL,'{"material_service":"Aerospace fasteners and hardware","single_source":"No","alternate_supplier":"Bolt & Rivet Co.","lead_time":"3 weeks","minimum_inventory":"6 weeks","current_inventory":"7 weeks","emergency_contact":"+1 555 0163","quality_approval":"Both sources approved"}'::jsonb),
    (cid,'supplier','Cascade Precision (outside processing)','Operations','Machining and inspection backup','high',true,'Standing capacity agreement — 7-day lead, expedite to 3 days for AOG',168,NULL,current_date - 60,'Doubles as the equipment recovery strategy','{"material_service":"Outside machining and sub-contract inspection","single_source":"No","lead_time":"7 days","emergency_contact":"+1 555 0177","quality_approval":"AS9100 certified, approved"}'::jsonb),
    (cid,'supplier','Northstar IT (managed service provider)','IT','ERP / MOM availability','critical',true,'Contracted 4h response; off-site backup custody',8,4,current_date - 30,NULL,'{"material_service":"IT support, backup custody, cyber response","single_source":"Yes","alternate_supplier":"Beacon Cyber (incident retainer)","emergency_contact":"+1 555 0121, 24h"}'::jsonb),
    (cid,'skill','5-axis CNC programming','Engineering','CNC machining','critical',false,'Contract programmer identified but not yet retained',72,NULL,NULL,'Highest people risk on site','{"primary_employee":"R. Alvarez","backup_employee":"None","training_required":"CAM 5-axis post-processor training","current_qualification":"Primary only","cross_training_required":"Yes — 2 candidates identified","minimum_staffing":"1","external_resource":"Contract programmer, 48h call"}'::jsonb),
    (cid,'skill','CMM programming and inspection','Quality','Product release','critical',true,'Two qualified inspectors plus sub-contract capability',24,NULL,current_date - 75,NULL,'{"primary_employee":"S. Patel","backup_employee":"A. Devine","second_backup":"Sub-contract — Cascade Precision","current_qualification":"Both current","minimum_staffing":"1 per shift"}'::jsonb),
    (cid,'skill','Special process — heat treat oversight','Quality','Machining and assembly','high',true,'Backup trained; approved sub-contract heat treater',48,NULL,current_date - 150,NULL,'{"primary_employee":"S. Patel","backup_employee":"R. Alvarez","training_required":"Nadcap awareness refresh","minimum_staffing":"1"}'::jsonb),
    (cid,'skill','ERP administration','IT','ERP / MOM availability','high',true,'MSP holds a second administrator account',24,NULL,current_date - 30,NULL,'{"primary_employee":"D. Brooks","backup_employee":"Northstar IT","current_qualification":"Current","minimum_staffing":"1","external_resource":"Northstar IT"}'::jsonb),
    (cid,'it_system','ERP / MOM','IT','All order flow','critical',true,'Nightly off-site backups; restore to cloud instance; paper travelers for up to 3 days',8,4,current_date - 30,'Restore tested in the functional exercise; took 11 hours against an 8-hour RTO','{"system_owner":"D. Brooks","hosting":"On-premise server + cloud replica","backup_method":"Nightly full, 4-hourly incremental","backup_location":"Off-site cloud (immutable copy)","manual_fallback":"Paper travelers, manual pick lists, offline shipping log","support_contact":"Northstar IT +1 555 0121"}'::jsonb),
    (cid,'it_system','Quality records and certification archive','Quality','Product release','critical',true,'Cloud archive with versioning; certs retrievable from the customer portal',12,4,current_date - 30,NULL,'{"system_owner":"S. Patel","hosting":"Cloud","backup_method":"Continuous versioning","backup_location":"Cloud region replica","manual_fallback":"Scanned paper certs held for 12 months","support_contact":"Northstar IT"}'::jsonb),
    (cid,'it_system','Site network and internet','IT','All systems','high',true,'Cellular failover router, tested monthly',2,NULL,current_date - 12,NULL,'{"system_owner":"D. Brooks","hosting":"On-premise","backup_method":"Config backup weekly","manual_fallback":"Cellular hotspot for shipping portals","support_contact":"Northstar IT"}'::jsonb);

  INSERT INTO public.bcm_incidents
    (company_id, ref, title, occurred_at, activation_level, incident_commander, location, description, safety_impact, facility_impact, equipment_impact, it_impact, production_impact, supply_chain_impact, customer_impact, immediate_actions, decisions, communications, recovery_actions, final_resolution, lessons_learned, status, recovery_hours, closed_at)
  VALUES
    (cid,'BC-2026-001','Regional power outage — 6 hours', now() - interval '54 days', 2,'J. Whitfield','Whole site','Storm-related substation fault took the site off supply at 13:40 on a Tuesday.','No injuries. Emergency lighting worked; two employees escorted from the CMM lab.','Building dark; HVAC off for 6 hours.','Two in-process parts scrapped when the mills lost position. CMM required re-warm-up.','Servers ran on UPS for 22 minutes then shut down cleanly.','Half a shift lost across both cells; 41 units behind plan.','No impact — no inbound or outbound movements scheduled.','Two shipments slipped by one day; both customers notified the same afternoon.','Accounted for all employees, stopped machines safely, sent non-essential staff home at 15:00.','Ran the second shift on Saturday to recover the schedule rather than expedite outside processing.','Employees by SMS; two customers by phone and email the same day.','Restarted in the pre-agreed sequence: servers, CMM lab HVAC, compressed air, machining.','Full production restored by 08:00 the following day.','No generator meant the CMM lab lost temperature control and cost 3 extra hours of warm-up. Generator sizing quote raised as an action.','closed',18, now() - interval '53 days'),
    (cid,'BC-2026-002','MC-104 spindle bearing failure', now() - interval '17 days', 1,'R. Alvarez','Machining cell','Vibration alarm followed by audible bearing noise during a wing-rib run.','None.','None.','Spindle cartridge failed; machine down 9 days awaiting the rebuild.','None.','Wing-rib family stopped; 3 orders moved to outside processing.','Outside processing capacity consumed at Cascade Precision.','One customer accepted a 5-day slip; one AOG order was expedited at our cost.','Stopped the machine, quarantined the in-process part, called Meridian service.','Approved a $14k expedited spindle rebuild rather than a 4-week standard lead.','Daily status to the two affected customers; internal stand-up each morning.','Outside processing for 3 orders; requalification run and first-article inspection after repair.','Machine back in production; Quality approved restart after FAI.','Vibration trending was not being reviewed monthly — it would have caught this. Monthly trending is now a PM step, and a rebuilt spindle is being held on site.','closed',216, now() - interval '8 days');

  SELECT id INTO i1 FROM public.bcm_incidents WHERE company_id=cid AND ref='BC-2026-001';
  SELECT id INTO i2 FROM public.bcm_incidents WHERE company_id=cid AND ref='BC-2026-002';

  INSERT INTO public.bcm_exercises
    (company_id, title, exercise_type, exercise_date, scenario, objectives, participants, expected_actions, actual_actions, what_worked, what_failed, lessons_learned, next_exercise)
  VALUES
    (cid,'Tabletop — major power outage at 14:00','tabletop', current_date - 70,'A regional outage removes power for 12 hours during peak production.','Test the activation process, decision-making and customer communication.','Site leader, Operations, EHS, Maintenance, Quality, IT, Supply chain','Activate Level 2, account for employees, set restart priorities, notify customers within 4 hours.','Team activated in 12 minutes; restart sequence agreed; customer list took 35 minutes to assemble.','Activation levels and incident command were clear. Restart sequence was agreed and later used for real.','No pre-built customer contact list; nobody owned external communication.','A pre-approved customer contact list and a named communications owner are now part of the plan.', current_date + 20),
    (cid,'Functional — ERP restore from off-site backup','functional', current_date - 30,'ERP server is unrecoverable; restore the latest off-site backup to the cloud instance.','Verify the 8-hour RTO and 4-hour RPO are achievable.','IT lead, Northstar IT, Operations, Quality','Restore within 8 hours with no more than 4 hours of data loss.','Restore completed in 11 hours; data loss was 3 hours.','Backups were valid and complete; RPO met comfortably.','RTO missed by 3 hours — DNS and licence reactivation were not documented.','Document the DNS and licence steps in the recovery runbook and re-test within 90 days.', current_date + 60);

  SELECT id INTO e1 FROM public.bcm_exercises WHERE company_id=cid AND exercise_type='tabletop';
  SELECT id INTO e2 FROM public.bcm_exercises WHERE company_id=cid AND exercise_type='functional';

  SELECT id INTO r1 FROM public.bcm_risks WHERE company_id=cid AND category='technology' AND risk ILIKE 'Ransomware%';
  SELECT id INTO r2 FROM public.bcm_risks WHERE company_id=cid AND risk ILIKE 'Alpine Metals%';
  SELECT id INTO r3 FROM public.bcm_risks WHERE company_id=cid AND risk ILIKE 'Extended power%';

  INSERT INTO public.bcm_actions (company_id, source_kind, risk_id, incident_id, exercise_id, action, owner_name, due_date, status, notes)
  VALUES
    (cid,'risk',r1,NULL,NULL,'Implement immutable off-site backup copies and segment the shop-floor network','D. Brooks', current_date + 21,'in_progress','Quoted; MSP scheduled for next month'),
    (cid,'risk',r1,NULL,NULL,'Run a quarterly phishing simulation for all email users','L. Moreau', current_date + 45,'open',NULL),
    (cid,'risk',r2,NULL,NULL,'Submit Ridgeline Alloys for customer source approval on 7075-T6','T. Okafor', current_date + 90,'open','Requires two lots of qualification data'),
    (cid,'risk',r3,NULL,NULL,'Obtain generator quotes sized for CMM lab, servers and one machining cell','J. Whitfield', current_date + 45,'in_progress','Two quotes received'),
    (cid,'incident',NULL,i1,NULL,'Build a pre-approved customer contact and notification list','M. Nguyen', current_date - 5,'open','Overdue — raised at the last review'),
    (cid,'incident',NULL,i2,NULL,'Add monthly vibration trending to the MC-104 PM routine','J. Whitfield', current_date - 12,'done','Completed and verified in the July PM'),
    (cid,'incident',NULL,i2,NULL,'Hold a rebuilt spindle cartridge on site','R. Alvarez', current_date + 30,'in_progress','Ordered, 6-week lead'),
    (cid,'exercise',NULL,NULL,e1,'Name a communications owner in the continuity team roster','L. Moreau', current_date + 10,'open',NULL),
    (cid,'exercise',NULL,NULL,e2,'Document DNS and licence reactivation steps in the IT recovery runbook and re-test','D. Brooks', current_date + 60,'open','Re-test scheduled with Northstar IT');

  ALTER TABLE public.bcm_processes ENABLE TRIGGER bcm_processes_template_lock;
  ALTER TABLE public.bcm_risks ENABLE TRIGGER bcm_risks_template_lock;
  ALTER TABLE public.bcm_assets ENABLE TRIGGER bcm_assets_template_lock;
  ALTER TABLE public.bcm_incidents ENABLE TRIGGER bcm_incidents_template_lock;
  ALTER TABLE public.bcm_exercises ENABLE TRIGGER bcm_exercises_template_lock;
  ALTER TABLE public.bcm_actions ENABLE TRIGGER bcm_actions_template_lock;
END $$;