/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedFloorRouteImport } from './routes/_authenticated/floor'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedActionsRouteRouteImport } from './routes/_authenticated/actions/route'
import { Route as AuthenticatedStrategyIndexRouteImport } from './routes/_authenticated/strategy/index'
import { Route as AuthenticatedReportIndexRouteImport } from './routes/_authenticated/report/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedOmsIndexRouteImport } from './routes/_authenticated/oms/index'
import { Route as AuthenticatedMeetingIndexRouteImport } from './routes/_authenticated/meeting/index'
import { Route as AuthenticatedCommercialIndexRouteImport } from './routes/_authenticated/commercial/index'
import { Route as AuthenticatedActionsIndexRouteImport } from './routes/_authenticated/actions/index'
import { Route as AuthenticatedStrategyWaterfallRouteImport } from './routes/_authenticated/strategy/waterfall'
import { Route as AuthenticatedStrategyRestructuringRouteImport } from './routes/_authenticated/strategy/restructuring'
import { Route as AuthenticatedStrategyInitiativesRouteImport } from './routes/_authenticated/strategy/initiatives'
import { Route as AuthenticatedStrategyHoshinRouteImport } from './routes/_authenticated/strategy/hoshin'
import { Route as AuthenticatedStrategyConsolidationRouteImport } from './routes/_authenticated/strategy/consolidation'
import { Route as AuthenticatedStrategyCapexRouteImport } from './routes/_authenticated/strategy/capex'
import { Route as AuthenticatedReportOwnerRouteImport } from './routes/_authenticated/report/owner'
import { Route as AuthenticatedReportIndustrialStrategyRouteImport } from './routes/_authenticated/report/industrial-strategy'
import { Route as AuthenticatedReportEnterpriseNetworkRouteImport } from './routes/_authenticated/report/enterprise-network'
import { Route as AuthenticatedReportBusinessHealthRouteImport } from './routes/_authenticated/report/business-health'
import { Route as AuthenticatedReportBoardRouteImport } from './routes/_authenticated/report/board'
import { Route as AuthenticatedPeopleSkillsRouteImport } from './routes/_authenticated/people/skills'
import { Route as AuthenticatedPeopleRolesRouteImport } from './routes/_authenticated/people/roles'
import { Route as AuthenticatedPeopleOrgChartRouteImport } from './routes/_authenticated/people/org-chart'
import { Route as AuthenticatedPeopleMatrixRouteImport } from './routes/_authenticated/people/matrix'
import { Route as AuthenticatedPeopleLeadershipRouteImport } from './routes/_authenticated/people/leadership'
import { Route as AuthenticatedPeopleImportRouteImport } from './routes/_authenticated/people/import'
import { Route as AuthenticatedPeopleGapsRouteImport } from './routes/_authenticated/people/gaps'
import { Route as AuthenticatedPeopleEngagementRouteImport } from './routes/_authenticated/people/engagement'
import { Route as AuthenticatedPeopleEmployeesRouteImport } from './routes/_authenticated/people/employees'
import { Route as AuthenticatedPeopleDevelopmentRouteImport } from './routes/_authenticated/people/development'
import { Route as AuthenticatedPeopleCertificationsRouteImport } from './routes/_authenticated/people/certifications'
import { Route as AuthenticatedOmsVsmRouteImport } from './routes/_authenticated/oms/vsm'
import { Route as AuthenticatedOmsSupplyChainRouteImport } from './routes/_authenticated/oms/supply-chain'
import { Route as AuthenticatedOmsStandardWorkRouteImport } from './routes/_authenticated/oms/standard-work'
import { Route as AuthenticatedOmsSiopRouteImport } from './routes/_authenticated/oms/siop'
import { Route as AuthenticatedOmsSicRouteImport } from './routes/_authenticated/oms/sic'
import { Route as AuthenticatedOmsShopfloorRouteImport } from './routes/_authenticated/oms/shopfloor'
import { Route as AuthenticatedOmsSchedulingRouteImport } from './routes/_authenticated/oms/scheduling'
import { Route as AuthenticatedOmsRiskRouteImport } from './routes/_authenticated/oms/risk'
import { Route as AuthenticatedOmsQualityRouteImport } from './routes/_authenticated/oms/quality'
import { Route as AuthenticatedOmsNpiRouteImport } from './routes/_authenticated/oms/npi'
import { Route as AuthenticatedOmsKpisRouteImport } from './routes/_authenticated/oms/kpis'
import { Route as AuthenticatedOmsIndustrializationRouteImport } from './routes/_authenticated/oms/industrialization'
import { Route as AuthenticatedOmsEndOfLifeRouteImport } from './routes/_authenticated/oms/end-of-life'
import { Route as AuthenticatedOmsDailyRouteImport } from './routes/_authenticated/oms/daily'
import { Route as AuthenticatedOmsCriticalPathRouteImport } from './routes/_authenticated/oms/critical-path'
import { Route as AuthenticatedOmsComplianceRouteImport } from './routes/_authenticated/oms/compliance'
import { Route as AuthenticatedMeetingWeeklyRouteImport } from './routes/_authenticated/meeting/weekly'
import { Route as AuthenticatedCommercialVocRouteImport } from './routes/_authenticated/commercial/voc'
import { Route as AuthenticatedCommercialStakeholdersRouteImport } from './routes/_authenticated/commercial/stakeholders'
import { Route as AuthenticatedCommercialReviewRouteImport } from './routes/_authenticated/commercial/review'
import { Route as AuthenticatedCommercialPlanRouteImport } from './routes/_authenticated/commercial/plan'
import { Route as AuthenticatedCommercialOpportunitiesRouteImport } from './routes/_authenticated/commercial/opportunities'
import { Route as AuthenticatedCommercialContractsRouteImport } from './routes/_authenticated/commercial/contracts'
import { Route as AuthenticatedReportTeamRoomIndexRouteImport } from './routes/_authenticated/report/team-room.index'
import { Route as AuthenticatedCommercialAccountsIndexRouteImport } from './routes/_authenticated/commercial/accounts.index'
import { Route as AuthenticatedActionsProblemSolverIndexRouteImport } from './routes/_authenticated/actions/problem-solver.index'
import { Route as AuthenticatedActionsPlaybookIndexRouteImport } from './routes/_authenticated/actions/playbook.index'
import { Route as AuthenticatedActionsCalculatorsIndexRouteImport } from './routes/_authenticated/actions/calculators.index'
import { Route as AuthenticatedReportTeamRoomThreadIdRouteImport } from './routes/_authenticated/report/team-room.$threadId'
import { Route as AuthenticatedPeopleEmployeesIdRouteImport } from './routes/_authenticated/people/employees.$id'
import { Route as AuthenticatedOmsPillarsPillarKeyRouteImport } from './routes/_authenticated/oms/pillars.$pillarKey'
import { Route as AuthenticatedCommercialAccountsIdRouteImport } from './routes/_authenticated/commercial/accounts.$id'
import { Route as AuthenticatedActionsProblemSolverMroRouteImport } from './routes/_authenticated/actions/problem-solver.mro'
import { Route as AuthenticatedActionsProblemSolverFiveWhysRouteImport } from './routes/_authenticated/actions/problem-solver.five-whys'
import { Route as AuthenticatedActionsProblemSolverFishboneRouteImport } from './routes/_authenticated/actions/problem-solver.fishbone'
import { Route as AuthenticatedActionsProblemSolverEightDRouteImport } from './routes/_authenticated/actions/problem-solver.eight-d'
import { Route as AuthenticatedActionsProblemSolverDmaicRouteImport } from './routes/_authenticated/actions/problem-solver.dmaic'
import { Route as AuthenticatedActionsProblemSolverA3RouteImport } from './routes/_authenticated/actions/problem-solver.a3'
import { Route as AuthenticatedActionsPlaybookIdRouteImport } from './routes/_authenticated/actions/playbook.$id'
import { Route as AuthenticatedActionsCalculatorsTaktRouteImport } from './routes/_authenticated/actions/calculators.takt'
import { Route as AuthenticatedActionsCalculatorsOeeRouteImport } from './routes/_authenticated/actions/calculators.oee'
import { Route as AuthenticatedActionsCalculatorsDowntimeRouteImport } from './routes/_authenticated/actions/calculators.downtime'
import { Route as AuthenticatedActionsCalculatorsCopqRouteImport } from './routes/_authenticated/actions/calculators.copq'
import { Route as AuthenticatedActionsCalculatorsChangeoverRouteImport } from './routes/_authenticated/actions/calculators.changeover'
import { Route as AuthenticatedActionsProblemSolverToolkitIndexRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.index'
import { Route as AuthenticatedActionsProblemSolverFlowsIndexRouteImport } from './routes/_authenticated/actions/problem-solver.flows.index'
import { Route as AuthenticatedActionsProblemSolverToolkitTocRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.toc'
import { Route as AuthenticatedActionsProblemSolverToolkitJourneyRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.journey'
import { Route as AuthenticatedActionsProblemSolverToolkitIbpRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.ibp'
import { Route as AuthenticatedActionsProblemSolverToolkitHoshinRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.hoshin'
import { Route as AuthenticatedActionsProblemSolverToolkitCldRouteImport } from './routes/_authenticated/actions/problem-solver.toolkit.cld'
import { Route as AuthenticatedActionsProblemSolverFlowsIdRouteImport } from './routes/_authenticated/actions/problem-solver.flows.$id'

const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFloorRoute = AuthenticatedFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionsRouteRoute =
  AuthenticatedActionsRouteRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyIndexRoute =
  AuthenticatedStrategyIndexRouteImport.update({
    id: '/strategy/',
    path: '/strategy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsIndexRoute = AuthenticatedOmsIndexRouteImport.update({
  id: '/oms/',
  path: '/oms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingIndexRoute =
  AuthenticatedMeetingIndexRouteImport.update({
    id: '/meeting/',
    path: '/meeting/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialIndexRoute =
  AuthenticatedCommercialIndexRouteImport.update({
    id: '/commercial/',
    path: '/commercial/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionsIndexRoute =
  AuthenticatedActionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedStrategyWaterfallRoute =
  AuthenticatedStrategyWaterfallRouteImport.update({
    id: '/strategy/waterfall',
    path: '/strategy/waterfall',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyRestructuringRoute =
  AuthenticatedStrategyRestructuringRouteImport.update({
    id: '/strategy/restructuring',
    path: '/strategy/restructuring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyInitiativesRoute =
  AuthenticatedStrategyInitiativesRouteImport.update({
    id: '/strategy/initiatives',
    path: '/strategy/initiatives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyHoshinRoute =
  AuthenticatedStrategyHoshinRouteImport.update({
    id: '/strategy/hoshin',
    path: '/strategy/hoshin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyConsolidationRoute =
  AuthenticatedStrategyConsolidationRouteImport.update({
    id: '/strategy/consolidation',
    path: '/strategy/consolidation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyCapexRoute =
  AuthenticatedStrategyCapexRouteImport.update({
    id: '/strategy/capex',
    path: '/strategy/capex',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportOwnerRoute =
  AuthenticatedReportOwnerRouteImport.update({
    id: '/report/owner',
    path: '/report/owner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIndustrialStrategyRoute =
  AuthenticatedReportIndustrialStrategyRouteImport.update({
    id: '/report/industrial-strategy',
    path: '/report/industrial-strategy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportEnterpriseNetworkRoute =
  AuthenticatedReportEnterpriseNetworkRouteImport.update({
    id: '/report/enterprise-network',
    path: '/report/enterprise-network',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportBusinessHealthRoute =
  AuthenticatedReportBusinessHealthRouteImport.update({
    id: '/report/business-health',
    path: '/report/business-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportBoardRoute =
  AuthenticatedReportBoardRouteImport.update({
    id: '/report/board',
    path: '/report/board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleSkillsRoute =
  AuthenticatedPeopleSkillsRouteImport.update({
    id: '/people/skills',
    path: '/people/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleRolesRoute =
  AuthenticatedPeopleRolesRouteImport.update({
    id: '/people/roles',
    path: '/people/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleOrgChartRoute =
  AuthenticatedPeopleOrgChartRouteImport.update({
    id: '/people/org-chart',
    path: '/people/org-chart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleMatrixRoute =
  AuthenticatedPeopleMatrixRouteImport.update({
    id: '/people/matrix',
    path: '/people/matrix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleLeadershipRoute =
  AuthenticatedPeopleLeadershipRouteImport.update({
    id: '/people/leadership',
    path: '/people/leadership',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleImportRoute =
  AuthenticatedPeopleImportRouteImport.update({
    id: '/people/import',
    path: '/people/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleGapsRoute = AuthenticatedPeopleGapsRouteImport.update({
  id: '/people/gaps',
  path: '/people/gaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleEngagementRoute =
  AuthenticatedPeopleEngagementRouteImport.update({
    id: '/people/engagement',
    path: '/people/engagement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleEmployeesRoute =
  AuthenticatedPeopleEmployeesRouteImport.update({
    id: '/people/employees',
    path: '/people/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleDevelopmentRoute =
  AuthenticatedPeopleDevelopmentRouteImport.update({
    id: '/people/development',
    path: '/people/development',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleCertificationsRoute =
  AuthenticatedPeopleCertificationsRouteImport.update({
    id: '/people/certifications',
    path: '/people/certifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsVsmRoute = AuthenticatedOmsVsmRouteImport.update({
  id: '/oms/vsm',
  path: '/oms/vsm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsSupplyChainRoute =
  AuthenticatedOmsSupplyChainRouteImport.update({
    id: '/oms/supply-chain',
    path: '/oms/supply-chain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsStandardWorkRoute =
  AuthenticatedOmsStandardWorkRouteImport.update({
    id: '/oms/standard-work',
    path: '/oms/standard-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsSiopRoute = AuthenticatedOmsSiopRouteImport.update({
  id: '/oms/siop',
  path: '/oms/siop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsSicRoute = AuthenticatedOmsSicRouteImport.update({
  id: '/oms/sic',
  path: '/oms/sic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsShopfloorRoute =
  AuthenticatedOmsShopfloorRouteImport.update({
    id: '/oms/shopfloor',
    path: '/oms/shopfloor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsSchedulingRoute =
  AuthenticatedOmsSchedulingRouteImport.update({
    id: '/oms/scheduling',
    path: '/oms/scheduling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsRiskRoute = AuthenticatedOmsRiskRouteImport.update({
  id: '/oms/risk',
  path: '/oms/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsQualityRoute = AuthenticatedOmsQualityRouteImport.update({
  id: '/oms/quality',
  path: '/oms/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsNpiRoute = AuthenticatedOmsNpiRouteImport.update({
  id: '/oms/npi',
  path: '/oms/npi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsKpisRoute = AuthenticatedOmsKpisRouteImport.update({
  id: '/oms/kpis',
  path: '/oms/kpis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsIndustrializationRoute =
  AuthenticatedOmsIndustrializationRouteImport.update({
    id: '/oms/industrialization',
    path: '/oms/industrialization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsEndOfLifeRoute =
  AuthenticatedOmsEndOfLifeRouteImport.update({
    id: '/oms/end-of-life',
    path: '/oms/end-of-life',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsDailyRoute = AuthenticatedOmsDailyRouteImport.update({
  id: '/oms/daily',
  path: '/oms/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmsCriticalPathRoute =
  AuthenticatedOmsCriticalPathRouteImport.update({
    id: '/oms/critical-path',
    path: '/oms/critical-path',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmsComplianceRoute =
  AuthenticatedOmsComplianceRouteImport.update({
    id: '/oms/compliance',
    path: '/oms/compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingWeeklyRoute =
  AuthenticatedMeetingWeeklyRouteImport.update({
    id: '/meeting/weekly',
    path: '/meeting/weekly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialVocRoute =
  AuthenticatedCommercialVocRouteImport.update({
    id: '/commercial/voc',
    path: '/commercial/voc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialStakeholdersRoute =
  AuthenticatedCommercialStakeholdersRouteImport.update({
    id: '/commercial/stakeholders',
    path: '/commercial/stakeholders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialReviewRoute =
  AuthenticatedCommercialReviewRouteImport.update({
    id: '/commercial/review',
    path: '/commercial/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialPlanRoute =
  AuthenticatedCommercialPlanRouteImport.update({
    id: '/commercial/plan',
    path: '/commercial/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialOpportunitiesRoute =
  AuthenticatedCommercialOpportunitiesRouteImport.update({
    id: '/commercial/opportunities',
    path: '/commercial/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialContractsRoute =
  AuthenticatedCommercialContractsRouteImport.update({
    id: '/commercial/contracts',
    path: '/commercial/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportTeamRoomIndexRoute =
  AuthenticatedReportTeamRoomIndexRouteImport.update({
    id: '/report/team-room/',
    path: '/report/team-room/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialAccountsIndexRoute =
  AuthenticatedCommercialAccountsIndexRouteImport.update({
    id: '/commercial/accounts/',
    path: '/commercial/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverIndexRoute =
  AuthenticatedActionsProblemSolverIndexRouteImport.update({
    id: '/problem-solver/',
    path: '/problem-solver/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsPlaybookIndexRoute =
  AuthenticatedActionsPlaybookIndexRouteImport.update({
    id: '/playbook/',
    path: '/playbook/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsIndexRoute =
  AuthenticatedActionsCalculatorsIndexRouteImport.update({
    id: '/calculators/',
    path: '/calculators/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedReportTeamRoomThreadIdRoute =
  AuthenticatedReportTeamRoomThreadIdRouteImport.update({
    id: '/report/team-room/$threadId',
    path: '/report/team-room/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleEmployeesIdRoute =
  AuthenticatedPeopleEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPeopleEmployeesRoute,
  } as any)
const AuthenticatedOmsPillarsPillarKeyRoute =
  AuthenticatedOmsPillarsPillarKeyRouteImport.update({
    id: '/oms/pillars/$pillarKey',
    path: '/oms/pillars/$pillarKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialAccountsIdRoute =
  AuthenticatedCommercialAccountsIdRouteImport.update({
    id: '/commercial/accounts/$id',
    path: '/commercial/accounts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverMroRoute =
  AuthenticatedActionsProblemSolverMroRouteImport.update({
    id: '/problem-solver/mro',
    path: '/problem-solver/mro',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverFiveWhysRoute =
  AuthenticatedActionsProblemSolverFiveWhysRouteImport.update({
    id: '/problem-solver/five-whys',
    path: '/problem-solver/five-whys',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverFishboneRoute =
  AuthenticatedActionsProblemSolverFishboneRouteImport.update({
    id: '/problem-solver/fishbone',
    path: '/problem-solver/fishbone',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverEightDRoute =
  AuthenticatedActionsProblemSolverEightDRouteImport.update({
    id: '/problem-solver/eight-d',
    path: '/problem-solver/eight-d',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverDmaicRoute =
  AuthenticatedActionsProblemSolverDmaicRouteImport.update({
    id: '/problem-solver/dmaic',
    path: '/problem-solver/dmaic',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverA3Route =
  AuthenticatedActionsProblemSolverA3RouteImport.update({
    id: '/problem-solver/a3',
    path: '/problem-solver/a3',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsPlaybookIdRoute =
  AuthenticatedActionsPlaybookIdRouteImport.update({
    id: '/playbook/$id',
    path: '/playbook/$id',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsTaktRoute =
  AuthenticatedActionsCalculatorsTaktRouteImport.update({
    id: '/calculators/takt',
    path: '/calculators/takt',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsOeeRoute =
  AuthenticatedActionsCalculatorsOeeRouteImport.update({
    id: '/calculators/oee',
    path: '/calculators/oee',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsDowntimeRoute =
  AuthenticatedActionsCalculatorsDowntimeRouteImport.update({
    id: '/calculators/downtime',
    path: '/calculators/downtime',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsCopqRoute =
  AuthenticatedActionsCalculatorsCopqRouteImport.update({
    id: '/calculators/copq',
    path: '/calculators/copq',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsCalculatorsChangeoverRoute =
  AuthenticatedActionsCalculatorsChangeoverRouteImport.update({
    id: '/calculators/changeover',
    path: '/calculators/changeover',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitIndexRoute =
  AuthenticatedActionsProblemSolverToolkitIndexRouteImport.update({
    id: '/problem-solver/toolkit/',
    path: '/problem-solver/toolkit/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverFlowsIndexRoute =
  AuthenticatedActionsProblemSolverFlowsIndexRouteImport.update({
    id: '/problem-solver/flows/',
    path: '/problem-solver/flows/',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitTocRoute =
  AuthenticatedActionsProblemSolverToolkitTocRouteImport.update({
    id: '/problem-solver/toolkit/toc',
    path: '/problem-solver/toolkit/toc',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitJourneyRoute =
  AuthenticatedActionsProblemSolverToolkitJourneyRouteImport.update({
    id: '/problem-solver/toolkit/journey',
    path: '/problem-solver/toolkit/journey',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitIbpRoute =
  AuthenticatedActionsProblemSolverToolkitIbpRouteImport.update({
    id: '/problem-solver/toolkit/ibp',
    path: '/problem-solver/toolkit/ibp',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitHoshinRoute =
  AuthenticatedActionsProblemSolverToolkitHoshinRouteImport.update({
    id: '/problem-solver/toolkit/hoshin',
    path: '/problem-solver/toolkit/hoshin',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverToolkitCldRoute =
  AuthenticatedActionsProblemSolverToolkitCldRouteImport.update({
    id: '/problem-solver/toolkit/cld',
    path: '/problem-solver/toolkit/cld',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)
const AuthenticatedActionsProblemSolverFlowsIdRoute =
  AuthenticatedActionsProblemSolverFlowsIdRouteImport.update({
    id: '/problem-solver/flows/$id',
    path: '/problem-solver/flows/$id',
    getParentRoute: () => AuthenticatedActionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-company': typeof SelectCompanyRoute
  '/actions': typeof AuthenticatedActionsRouteRouteWithChildren
  '/about': typeof AuthenticatedAboutRoute
  '/floor': typeof AuthenticatedFloorRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/commercial/contracts': typeof AuthenticatedCommercialContractsRoute
  '/commercial/opportunities': typeof AuthenticatedCommercialOpportunitiesRoute
  '/commercial/plan': typeof AuthenticatedCommercialPlanRoute
  '/commercial/review': typeof AuthenticatedCommercialReviewRoute
  '/commercial/stakeholders': typeof AuthenticatedCommercialStakeholdersRoute
  '/commercial/voc': typeof AuthenticatedCommercialVocRoute
  '/meeting/weekly': typeof AuthenticatedMeetingWeeklyRoute
  '/oms/compliance': typeof AuthenticatedOmsComplianceRoute
  '/oms/critical-path': typeof AuthenticatedOmsCriticalPathRoute
  '/oms/daily': typeof AuthenticatedOmsDailyRoute
  '/oms/end-of-life': typeof AuthenticatedOmsEndOfLifeRoute
  '/oms/industrialization': typeof AuthenticatedOmsIndustrializationRoute
  '/oms/kpis': typeof AuthenticatedOmsKpisRoute
  '/oms/npi': typeof AuthenticatedOmsNpiRoute
  '/oms/quality': typeof AuthenticatedOmsQualityRoute
  '/oms/risk': typeof AuthenticatedOmsRiskRoute
  '/oms/scheduling': typeof AuthenticatedOmsSchedulingRoute
  '/oms/shopfloor': typeof AuthenticatedOmsShopfloorRoute
  '/oms/sic': typeof AuthenticatedOmsSicRoute
  '/oms/siop': typeof AuthenticatedOmsSiopRoute
  '/oms/standard-work': typeof AuthenticatedOmsStandardWorkRoute
  '/oms/supply-chain': typeof AuthenticatedOmsSupplyChainRoute
  '/oms/vsm': typeof AuthenticatedOmsVsmRoute
  '/people/certifications': typeof AuthenticatedPeopleCertificationsRoute
  '/people/development': typeof AuthenticatedPeopleDevelopmentRoute
  '/people/employees': typeof AuthenticatedPeopleEmployeesRouteWithChildren
  '/people/engagement': typeof AuthenticatedPeopleEngagementRoute
  '/people/gaps': typeof AuthenticatedPeopleGapsRoute
  '/people/import': typeof AuthenticatedPeopleImportRoute
  '/people/leadership': typeof AuthenticatedPeopleLeadershipRoute
  '/people/matrix': typeof AuthenticatedPeopleMatrixRoute
  '/people/org-chart': typeof AuthenticatedPeopleOrgChartRoute
  '/people/roles': typeof AuthenticatedPeopleRolesRoute
  '/people/skills': typeof AuthenticatedPeopleSkillsRoute
  '/report/board': typeof AuthenticatedReportBoardRoute
  '/report/business-health': typeof AuthenticatedReportBusinessHealthRoute
  '/report/enterprise-network': typeof AuthenticatedReportEnterpriseNetworkRoute
  '/report/industrial-strategy': typeof AuthenticatedReportIndustrialStrategyRoute
  '/report/owner': typeof AuthenticatedReportOwnerRoute
  '/strategy/capex': typeof AuthenticatedStrategyCapexRoute
  '/strategy/consolidation': typeof AuthenticatedStrategyConsolidationRoute
  '/strategy/hoshin': typeof AuthenticatedStrategyHoshinRoute
  '/strategy/initiatives': typeof AuthenticatedStrategyInitiativesRoute
  '/strategy/restructuring': typeof AuthenticatedStrategyRestructuringRoute
  '/strategy/waterfall': typeof AuthenticatedStrategyWaterfallRoute
  '/actions/': typeof AuthenticatedActionsIndexRoute
  '/commercial/': typeof AuthenticatedCommercialIndexRoute
  '/meeting/': typeof AuthenticatedMeetingIndexRoute
  '/oms/': typeof AuthenticatedOmsIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/report/': typeof AuthenticatedReportIndexRoute
  '/strategy/': typeof AuthenticatedStrategyIndexRoute
  '/actions/calculators/changeover': typeof AuthenticatedActionsCalculatorsChangeoverRoute
  '/actions/calculators/copq': typeof AuthenticatedActionsCalculatorsCopqRoute
  '/actions/calculators/downtime': typeof AuthenticatedActionsCalculatorsDowntimeRoute
  '/actions/calculators/oee': typeof AuthenticatedActionsCalculatorsOeeRoute
  '/actions/calculators/takt': typeof AuthenticatedActionsCalculatorsTaktRoute
  '/actions/playbook/$id': typeof AuthenticatedActionsPlaybookIdRoute
  '/actions/problem-solver/a3': typeof AuthenticatedActionsProblemSolverA3Route
  '/actions/problem-solver/dmaic': typeof AuthenticatedActionsProblemSolverDmaicRoute
  '/actions/problem-solver/eight-d': typeof AuthenticatedActionsProblemSolverEightDRoute
  '/actions/problem-solver/fishbone': typeof AuthenticatedActionsProblemSolverFishboneRoute
  '/actions/problem-solver/five-whys': typeof AuthenticatedActionsProblemSolverFiveWhysRoute
  '/actions/problem-solver/mro': typeof AuthenticatedActionsProblemSolverMroRoute
  '/commercial/accounts/$id': typeof AuthenticatedCommercialAccountsIdRoute
  '/oms/pillars/$pillarKey': typeof AuthenticatedOmsPillarsPillarKeyRoute
  '/people/employees/$id': typeof AuthenticatedPeopleEmployeesIdRoute
  '/report/team-room/$threadId': typeof AuthenticatedReportTeamRoomThreadIdRoute
  '/actions/calculators/': typeof AuthenticatedActionsCalculatorsIndexRoute
  '/actions/playbook/': typeof AuthenticatedActionsPlaybookIndexRoute
  '/actions/problem-solver/': typeof AuthenticatedActionsProblemSolverIndexRoute
  '/commercial/accounts/': typeof AuthenticatedCommercialAccountsIndexRoute
  '/report/team-room/': typeof AuthenticatedReportTeamRoomIndexRoute
  '/actions/problem-solver/flows/$id': typeof AuthenticatedActionsProblemSolverFlowsIdRoute
  '/actions/problem-solver/toolkit/cld': typeof AuthenticatedActionsProblemSolverToolkitCldRoute
  '/actions/problem-solver/toolkit/hoshin': typeof AuthenticatedActionsProblemSolverToolkitHoshinRoute
  '/actions/problem-solver/toolkit/ibp': typeof AuthenticatedActionsProblemSolverToolkitIbpRoute
  '/actions/problem-solver/toolkit/journey': typeof AuthenticatedActionsProblemSolverToolkitJourneyRoute
  '/actions/problem-solver/toolkit/toc': typeof AuthenticatedActionsProblemSolverToolkitTocRoute
  '/actions/problem-solver/flows/': typeof AuthenticatedActionsProblemSolverFlowsIndexRoute
  '/actions/problem-solver/toolkit/': typeof AuthenticatedActionsProblemSolverToolkitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-company': typeof SelectCompanyRoute
  '/about': typeof AuthenticatedAboutRoute
  '/floor': typeof AuthenticatedFloorRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/commercial/contracts': typeof AuthenticatedCommercialContractsRoute
  '/commercial/opportunities': typeof AuthenticatedCommercialOpportunitiesRoute
  '/commercial/plan': typeof AuthenticatedCommercialPlanRoute
  '/commercial/review': typeof AuthenticatedCommercialReviewRoute
  '/commercial/stakeholders': typeof AuthenticatedCommercialStakeholdersRoute
  '/commercial/voc': typeof AuthenticatedCommercialVocRoute
  '/meeting/weekly': typeof AuthenticatedMeetingWeeklyRoute
  '/oms/compliance': typeof AuthenticatedOmsComplianceRoute
  '/oms/critical-path': typeof AuthenticatedOmsCriticalPathRoute
  '/oms/daily': typeof AuthenticatedOmsDailyRoute
  '/oms/end-of-life': typeof AuthenticatedOmsEndOfLifeRoute
  '/oms/industrialization': typeof AuthenticatedOmsIndustrializationRoute
  '/oms/kpis': typeof AuthenticatedOmsKpisRoute
  '/oms/npi': typeof AuthenticatedOmsNpiRoute
  '/oms/quality': typeof AuthenticatedOmsQualityRoute
  '/oms/risk': typeof AuthenticatedOmsRiskRoute
  '/oms/scheduling': typeof AuthenticatedOmsSchedulingRoute
  '/oms/shopfloor': typeof AuthenticatedOmsShopfloorRoute
  '/oms/sic': typeof AuthenticatedOmsSicRoute
  '/oms/siop': typeof AuthenticatedOmsSiopRoute
  '/oms/standard-work': typeof AuthenticatedOmsStandardWorkRoute
  '/oms/supply-chain': typeof AuthenticatedOmsSupplyChainRoute
  '/oms/vsm': typeof AuthenticatedOmsVsmRoute
  '/people/certifications': typeof AuthenticatedPeopleCertificationsRoute
  '/people/development': typeof AuthenticatedPeopleDevelopmentRoute
  '/people/employees': typeof AuthenticatedPeopleEmployeesRouteWithChildren
  '/people/engagement': typeof AuthenticatedPeopleEngagementRoute
  '/people/gaps': typeof AuthenticatedPeopleGapsRoute
  '/people/import': typeof AuthenticatedPeopleImportRoute
  '/people/leadership': typeof AuthenticatedPeopleLeadershipRoute
  '/people/matrix': typeof AuthenticatedPeopleMatrixRoute
  '/people/org-chart': typeof AuthenticatedPeopleOrgChartRoute
  '/people/roles': typeof AuthenticatedPeopleRolesRoute
  '/people/skills': typeof AuthenticatedPeopleSkillsRoute
  '/report/board': typeof AuthenticatedReportBoardRoute
  '/report/business-health': typeof AuthenticatedReportBusinessHealthRoute
  '/report/enterprise-network': typeof AuthenticatedReportEnterpriseNetworkRoute
  '/report/industrial-strategy': typeof AuthenticatedReportIndustrialStrategyRoute
  '/report/owner': typeof AuthenticatedReportOwnerRoute
  '/strategy/capex': typeof AuthenticatedStrategyCapexRoute
  '/strategy/consolidation': typeof AuthenticatedStrategyConsolidationRoute
  '/strategy/hoshin': typeof AuthenticatedStrategyHoshinRoute
  '/strategy/initiatives': typeof AuthenticatedStrategyInitiativesRoute
  '/strategy/restructuring': typeof AuthenticatedStrategyRestructuringRoute
  '/strategy/waterfall': typeof AuthenticatedStrategyWaterfallRoute
  '/actions': typeof AuthenticatedActionsIndexRoute
  '/commercial': typeof AuthenticatedCommercialIndexRoute
  '/meeting': typeof AuthenticatedMeetingIndexRoute
  '/oms': typeof AuthenticatedOmsIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/report': typeof AuthenticatedReportIndexRoute
  '/strategy': typeof AuthenticatedStrategyIndexRoute
  '/actions/calculators/changeover': typeof AuthenticatedActionsCalculatorsChangeoverRoute
  '/actions/calculators/copq': typeof AuthenticatedActionsCalculatorsCopqRoute
  '/actions/calculators/downtime': typeof AuthenticatedActionsCalculatorsDowntimeRoute
  '/actions/calculators/oee': typeof AuthenticatedActionsCalculatorsOeeRoute
  '/actions/calculators/takt': typeof AuthenticatedActionsCalculatorsTaktRoute
  '/actions/playbook/$id': typeof AuthenticatedActionsPlaybookIdRoute
  '/actions/problem-solver/a3': typeof AuthenticatedActionsProblemSolverA3Route
  '/actions/problem-solver/dmaic': typeof AuthenticatedActionsProblemSolverDmaicRoute
  '/actions/problem-solver/eight-d': typeof AuthenticatedActionsProblemSolverEightDRoute
  '/actions/problem-solver/fishbone': typeof AuthenticatedActionsProblemSolverFishboneRoute
  '/actions/problem-solver/five-whys': typeof AuthenticatedActionsProblemSolverFiveWhysRoute
  '/actions/problem-solver/mro': typeof AuthenticatedActionsProblemSolverMroRoute
  '/commercial/accounts/$id': typeof AuthenticatedCommercialAccountsIdRoute
  '/oms/pillars/$pillarKey': typeof AuthenticatedOmsPillarsPillarKeyRoute
  '/people/employees/$id': typeof AuthenticatedPeopleEmployeesIdRoute
  '/report/team-room/$threadId': typeof AuthenticatedReportTeamRoomThreadIdRoute
  '/actions/calculators': typeof AuthenticatedActionsCalculatorsIndexRoute
  '/actions/playbook': typeof AuthenticatedActionsPlaybookIndexRoute
  '/actions/problem-solver': typeof AuthenticatedActionsProblemSolverIndexRoute
  '/commercial/accounts': typeof AuthenticatedCommercialAccountsIndexRoute
  '/report/team-room': typeof AuthenticatedReportTeamRoomIndexRoute
  '/actions/problem-solver/flows/$id': typeof AuthenticatedActionsProblemSolverFlowsIdRoute
  '/actions/problem-solver/toolkit/cld': typeof AuthenticatedActionsProblemSolverToolkitCldRoute
  '/actions/problem-solver/toolkit/hoshin': typeof AuthenticatedActionsProblemSolverToolkitHoshinRoute
  '/actions/problem-solver/toolkit/ibp': typeof AuthenticatedActionsProblemSolverToolkitIbpRoute
  '/actions/problem-solver/toolkit/journey': typeof AuthenticatedActionsProblemSolverToolkitJourneyRoute
  '/actions/problem-solver/toolkit/toc': typeof AuthenticatedActionsProblemSolverToolkitTocRoute
  '/actions/problem-solver/flows': typeof AuthenticatedActionsProblemSolverFlowsIndexRoute
  '/actions/problem-solver/toolkit': typeof AuthenticatedActionsProblemSolverToolkitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/select-company': typeof SelectCompanyRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRouteRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/floor': typeof AuthenticatedFloorRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/commercial/contracts': typeof AuthenticatedCommercialContractsRoute
  '/_authenticated/commercial/opportunities': typeof AuthenticatedCommercialOpportunitiesRoute
  '/_authenticated/commercial/plan': typeof AuthenticatedCommercialPlanRoute
  '/_authenticated/commercial/review': typeof AuthenticatedCommercialReviewRoute
  '/_authenticated/commercial/stakeholders': typeof AuthenticatedCommercialStakeholdersRoute
  '/_authenticated/commercial/voc': typeof AuthenticatedCommercialVocRoute
  '/_authenticated/meeting/weekly': typeof AuthenticatedMeetingWeeklyRoute
  '/_authenticated/oms/compliance': typeof AuthenticatedOmsComplianceRoute
  '/_authenticated/oms/critical-path': typeof AuthenticatedOmsCriticalPathRoute
  '/_authenticated/oms/daily': typeof AuthenticatedOmsDailyRoute
  '/_authenticated/oms/end-of-life': typeof AuthenticatedOmsEndOfLifeRoute
  '/_authenticated/oms/industrialization': typeof AuthenticatedOmsIndustrializationRoute
  '/_authenticated/oms/kpis': typeof AuthenticatedOmsKpisRoute
  '/_authenticated/oms/npi': typeof AuthenticatedOmsNpiRoute
  '/_authenticated/oms/quality': typeof AuthenticatedOmsQualityRoute
  '/_authenticated/oms/risk': typeof AuthenticatedOmsRiskRoute
  '/_authenticated/oms/scheduling': typeof AuthenticatedOmsSchedulingRoute
  '/_authenticated/oms/shopfloor': typeof AuthenticatedOmsShopfloorRoute
  '/_authenticated/oms/sic': typeof AuthenticatedOmsSicRoute
  '/_authenticated/oms/siop': typeof AuthenticatedOmsSiopRoute
  '/_authenticated/oms/standard-work': typeof AuthenticatedOmsStandardWorkRoute
  '/_authenticated/oms/supply-chain': typeof AuthenticatedOmsSupplyChainRoute
  '/_authenticated/oms/vsm': typeof AuthenticatedOmsVsmRoute
  '/_authenticated/people/certifications': typeof AuthenticatedPeopleCertificationsRoute
  '/_authenticated/people/development': typeof AuthenticatedPeopleDevelopmentRoute
  '/_authenticated/people/employees': typeof AuthenticatedPeopleEmployeesRouteWithChildren
  '/_authenticated/people/engagement': typeof AuthenticatedPeopleEngagementRoute
  '/_authenticated/people/gaps': typeof AuthenticatedPeopleGapsRoute
  '/_authenticated/people/import': typeof AuthenticatedPeopleImportRoute
  '/_authenticated/people/leadership': typeof AuthenticatedPeopleLeadershipRoute
  '/_authenticated/people/matrix': typeof AuthenticatedPeopleMatrixRoute
  '/_authenticated/people/org-chart': typeof AuthenticatedPeopleOrgChartRoute
  '/_authenticated/people/roles': typeof AuthenticatedPeopleRolesRoute
  '/_authenticated/people/skills': typeof AuthenticatedPeopleSkillsRoute
  '/_authenticated/report/board': typeof AuthenticatedReportBoardRoute
  '/_authenticated/report/business-health': typeof AuthenticatedReportBusinessHealthRoute
  '/_authenticated/report/enterprise-network': typeof AuthenticatedReportEnterpriseNetworkRoute
  '/_authenticated/report/industrial-strategy': typeof AuthenticatedReportIndustrialStrategyRoute
  '/_authenticated/report/owner': typeof AuthenticatedReportOwnerRoute
  '/_authenticated/strategy/capex': typeof AuthenticatedStrategyCapexRoute
  '/_authenticated/strategy/consolidation': typeof AuthenticatedStrategyConsolidationRoute
  '/_authenticated/strategy/hoshin': typeof AuthenticatedStrategyHoshinRoute
  '/_authenticated/strategy/initiatives': typeof AuthenticatedStrategyInitiativesRoute
  '/_authenticated/strategy/restructuring': typeof AuthenticatedStrategyRestructuringRoute
  '/_authenticated/strategy/waterfall': typeof AuthenticatedStrategyWaterfallRoute
  '/_authenticated/actions/': typeof AuthenticatedActionsIndexRoute
  '/_authenticated/commercial/': typeof AuthenticatedCommercialIndexRoute
  '/_authenticated/meeting/': typeof AuthenticatedMeetingIndexRoute
  '/_authenticated/oms/': typeof AuthenticatedOmsIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
  '/_authenticated/strategy/': typeof AuthenticatedStrategyIndexRoute
  '/_authenticated/actions/calculators/changeover': typeof AuthenticatedActionsCalculatorsChangeoverRoute
  '/_authenticated/actions/calculators/copq': typeof AuthenticatedActionsCalculatorsCopqRoute
  '/_authenticated/actions/calculators/downtime': typeof AuthenticatedActionsCalculatorsDowntimeRoute
  '/_authenticated/actions/calculators/oee': typeof AuthenticatedActionsCalculatorsOeeRoute
  '/_authenticated/actions/calculators/takt': typeof AuthenticatedActionsCalculatorsTaktRoute
  '/_authenticated/actions/playbook/$id': typeof AuthenticatedActionsPlaybookIdRoute
  '/_authenticated/actions/problem-solver/a3': typeof AuthenticatedActionsProblemSolverA3Route
  '/_authenticated/actions/problem-solver/dmaic': typeof AuthenticatedActionsProblemSolverDmaicRoute
  '/_authenticated/actions/problem-solver/eight-d': typeof AuthenticatedActionsProblemSolverEightDRoute
  '/_authenticated/actions/problem-solver/fishbone': typeof AuthenticatedActionsProblemSolverFishboneRoute
  '/_authenticated/actions/problem-solver/five-whys': typeof AuthenticatedActionsProblemSolverFiveWhysRoute
  '/_authenticated/actions/problem-solver/mro': typeof AuthenticatedActionsProblemSolverMroRoute
  '/_authenticated/commercial/accounts/$id': typeof AuthenticatedCommercialAccountsIdRoute
  '/_authenticated/oms/pillars/$pillarKey': typeof AuthenticatedOmsPillarsPillarKeyRoute
  '/_authenticated/people/employees/$id': typeof AuthenticatedPeopleEmployeesIdRoute
  '/_authenticated/report/team-room/$threadId': typeof AuthenticatedReportTeamRoomThreadIdRoute
  '/_authenticated/actions/calculators/': typeof AuthenticatedActionsCalculatorsIndexRoute
  '/_authenticated/actions/playbook/': typeof AuthenticatedActionsPlaybookIndexRoute
  '/_authenticated/actions/problem-solver/': typeof AuthenticatedActionsProblemSolverIndexRoute
  '/_authenticated/commercial/accounts/': typeof AuthenticatedCommercialAccountsIndexRoute
  '/_authenticated/report/team-room/': typeof AuthenticatedReportTeamRoomIndexRoute
  '/_authenticated/actions/problem-solver/flows/$id': typeof AuthenticatedActionsProblemSolverFlowsIdRoute
  '/_authenticated/actions/problem-solver/toolkit/cld': typeof AuthenticatedActionsProblemSolverToolkitCldRoute
  '/_authenticated/actions/problem-solver/toolkit/hoshin': typeof AuthenticatedActionsProblemSolverToolkitHoshinRoute
  '/_authenticated/actions/problem-solver/toolkit/ibp': typeof AuthenticatedActionsProblemSolverToolkitIbpRoute
  '/_authenticated/actions/problem-solver/toolkit/journey': typeof AuthenticatedActionsProblemSolverToolkitJourneyRoute
  '/_authenticated/actions/problem-solver/toolkit/toc': typeof AuthenticatedActionsProblemSolverToolkitTocRoute
  '/_authenticated/actions/problem-solver/flows/': typeof AuthenticatedActionsProblemSolverFlowsIndexRoute
  '/_authenticated/actions/problem-solver/toolkit/': typeof AuthenticatedActionsProblemSolverToolkitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-company'
    | '/actions'
    | '/about'
    | '/floor'
    | '/overview'
    | '/settings'
    | '/support'
    | '/commercial/contracts'
    | '/commercial/opportunities'
    | '/commercial/plan'
    | '/commercial/review'
    | '/commercial/stakeholders'
    | '/commercial/voc'
    | '/meeting/weekly'
    | '/oms/compliance'
    | '/oms/critical-path'
    | '/oms/daily'
    | '/oms/end-of-life'
    | '/oms/industrialization'
    | '/oms/kpis'
    | '/oms/npi'
    | '/oms/quality'
    | '/oms/risk'
    | '/oms/scheduling'
    | '/oms/shopfloor'
    | '/oms/sic'
    | '/oms/siop'
    | '/oms/standard-work'
    | '/oms/supply-chain'
    | '/oms/vsm'
    | '/people/certifications'
    | '/people/development'
    | '/people/employees'
    | '/people/engagement'
    | '/people/gaps'
    | '/people/import'
    | '/people/leadership'
    | '/people/matrix'
    | '/people/org-chart'
    | '/people/roles'
    | '/people/skills'
    | '/report/board'
    | '/report/business-health'
    | '/report/enterprise-network'
    | '/report/industrial-strategy'
    | '/report/owner'
    | '/strategy/capex'
    | '/strategy/consolidation'
    | '/strategy/hoshin'
    | '/strategy/initiatives'
    | '/strategy/restructuring'
    | '/strategy/waterfall'
    | '/actions/'
    | '/commercial/'
    | '/meeting/'
    | '/oms/'
    | '/people/'
    | '/report/'
    | '/strategy/'
    | '/actions/calculators/changeover'
    | '/actions/calculators/copq'
    | '/actions/calculators/downtime'
    | '/actions/calculators/oee'
    | '/actions/calculators/takt'
    | '/actions/playbook/$id'
    | '/actions/problem-solver/a3'
    | '/actions/problem-solver/dmaic'
    | '/actions/problem-solver/eight-d'
    | '/actions/problem-solver/fishbone'
    | '/actions/problem-solver/five-whys'
    | '/actions/problem-solver/mro'
    | '/commercial/accounts/$id'
    | '/oms/pillars/$pillarKey'
    | '/people/employees/$id'
    | '/report/team-room/$threadId'
    | '/actions/calculators/'
    | '/actions/playbook/'
    | '/actions/problem-solver/'
    | '/commercial/accounts/'
    | '/report/team-room/'
    | '/actions/problem-solver/flows/$id'
    | '/actions/problem-solver/toolkit/cld'
    | '/actions/problem-solver/toolkit/hoshin'
    | '/actions/problem-solver/toolkit/ibp'
    | '/actions/problem-solver/toolkit/journey'
    | '/actions/problem-solver/toolkit/toc'
    | '/actions/problem-solver/flows/'
    | '/actions/problem-solver/toolkit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-company'
    | '/about'
    | '/floor'
    | '/overview'
    | '/settings'
    | '/support'
    | '/commercial/contracts'
    | '/commercial/opportunities'
    | '/commercial/plan'
    | '/commercial/review'
    | '/commercial/stakeholders'
    | '/commercial/voc'
    | '/meeting/weekly'
    | '/oms/compliance'
    | '/oms/critical-path'
    | '/oms/daily'
    | '/oms/end-of-life'
    | '/oms/industrialization'
    | '/oms/kpis'
    | '/oms/npi'
    | '/oms/quality'
    | '/oms/risk'
    | '/oms/scheduling'
    | '/oms/shopfloor'
    | '/oms/sic'
    | '/oms/siop'
    | '/oms/standard-work'
    | '/oms/supply-chain'
    | '/oms/vsm'
    | '/people/certifications'
    | '/people/development'
    | '/people/employees'
    | '/people/engagement'
    | '/people/gaps'
    | '/people/import'
    | '/people/leadership'
    | '/people/matrix'
    | '/people/org-chart'
    | '/people/roles'
    | '/people/skills'
    | '/report/board'
    | '/report/business-health'
    | '/report/enterprise-network'
    | '/report/industrial-strategy'
    | '/report/owner'
    | '/strategy/capex'
    | '/strategy/consolidation'
    | '/strategy/hoshin'
    | '/strategy/initiatives'
    | '/strategy/restructuring'
    | '/strategy/waterfall'
    | '/actions'
    | '/commercial'
    | '/meeting'
    | '/oms'
    | '/people'
    | '/report'
    | '/strategy'
    | '/actions/calculators/changeover'
    | '/actions/calculators/copq'
    | '/actions/calculators/downtime'
    | '/actions/calculators/oee'
    | '/actions/calculators/takt'
    | '/actions/playbook/$id'
    | '/actions/problem-solver/a3'
    | '/actions/problem-solver/dmaic'
    | '/actions/problem-solver/eight-d'
    | '/actions/problem-solver/fishbone'
    | '/actions/problem-solver/five-whys'
    | '/actions/problem-solver/mro'
    | '/commercial/accounts/$id'
    | '/oms/pillars/$pillarKey'
    | '/people/employees/$id'
    | '/report/team-room/$threadId'
    | '/actions/calculators'
    | '/actions/playbook'
    | '/actions/problem-solver'
    | '/commercial/accounts'
    | '/report/team-room'
    | '/actions/problem-solver/flows/$id'
    | '/actions/problem-solver/toolkit/cld'
    | '/actions/problem-solver/toolkit/hoshin'
    | '/actions/problem-solver/toolkit/ibp'
    | '/actions/problem-solver/toolkit/journey'
    | '/actions/problem-solver/toolkit/toc'
    | '/actions/problem-solver/flows'
    | '/actions/problem-solver/toolkit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/select-company'
    | '/_authenticated/actions'
    | '/_authenticated/about'
    | '/_authenticated/floor'
    | '/_authenticated/overview'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/commercial/contracts'
    | '/_authenticated/commercial/opportunities'
    | '/_authenticated/commercial/plan'
    | '/_authenticated/commercial/review'
    | '/_authenticated/commercial/stakeholders'
    | '/_authenticated/commercial/voc'
    | '/_authenticated/meeting/weekly'
    | '/_authenticated/oms/compliance'
    | '/_authenticated/oms/critical-path'
    | '/_authenticated/oms/daily'
    | '/_authenticated/oms/end-of-life'
    | '/_authenticated/oms/industrialization'
    | '/_authenticated/oms/kpis'
    | '/_authenticated/oms/npi'
    | '/_authenticated/oms/quality'
    | '/_authenticated/oms/risk'
    | '/_authenticated/oms/scheduling'
    | '/_authenticated/oms/shopfloor'
    | '/_authenticated/oms/sic'
    | '/_authenticated/oms/siop'
    | '/_authenticated/oms/standard-work'
    | '/_authenticated/oms/supply-chain'
    | '/_authenticated/oms/vsm'
    | '/_authenticated/people/certifications'
    | '/_authenticated/people/development'
    | '/_authenticated/people/employees'
    | '/_authenticated/people/engagement'
    | '/_authenticated/people/gaps'
    | '/_authenticated/people/import'
    | '/_authenticated/people/leadership'
    | '/_authenticated/people/matrix'
    | '/_authenticated/people/org-chart'
    | '/_authenticated/people/roles'
    | '/_authenticated/people/skills'
    | '/_authenticated/report/board'
    | '/_authenticated/report/business-health'
    | '/_authenticated/report/enterprise-network'
    | '/_authenticated/report/industrial-strategy'
    | '/_authenticated/report/owner'
    | '/_authenticated/strategy/capex'
    | '/_authenticated/strategy/consolidation'
    | '/_authenticated/strategy/hoshin'
    | '/_authenticated/strategy/initiatives'
    | '/_authenticated/strategy/restructuring'
    | '/_authenticated/strategy/waterfall'
    | '/_authenticated/actions/'
    | '/_authenticated/commercial/'
    | '/_authenticated/meeting/'
    | '/_authenticated/oms/'
    | '/_authenticated/people/'
    | '/_authenticated/report/'
    | '/_authenticated/strategy/'
    | '/_authenticated/actions/calculators/changeover'
    | '/_authenticated/actions/calculators/copq'
    | '/_authenticated/actions/calculators/downtime'
    | '/_authenticated/actions/calculators/oee'
    | '/_authenticated/actions/calculators/takt'
    | '/_authenticated/actions/playbook/$id'
    | '/_authenticated/actions/problem-solver/a3'
    | '/_authenticated/actions/problem-solver/dmaic'
    | '/_authenticated/actions/problem-solver/eight-d'
    | '/_authenticated/actions/problem-solver/fishbone'
    | '/_authenticated/actions/problem-solver/five-whys'
    | '/_authenticated/actions/problem-solver/mro'
    | '/_authenticated/commercial/accounts/$id'
    | '/_authenticated/oms/pillars/$pillarKey'
    | '/_authenticated/people/employees/$id'
    | '/_authenticated/report/team-room/$threadId'
    | '/_authenticated/actions/calculators/'
    | '/_authenticated/actions/playbook/'
    | '/_authenticated/actions/problem-solver/'
    | '/_authenticated/commercial/accounts/'
    | '/_authenticated/report/team-room/'
    | '/_authenticated/actions/problem-solver/flows/$id'
    | '/_authenticated/actions/problem-solver/toolkit/cld'
    | '/_authenticated/actions/problem-solver/toolkit/hoshin'
    | '/_authenticated/actions/problem-solver/toolkit/ibp'
    | '/_authenticated/actions/problem-solver/toolkit/journey'
    | '/_authenticated/actions/problem-solver/toolkit/toc'
    | '/_authenticated/actions/problem-solver/flows/'
    | '/_authenticated/actions/problem-solver/toolkit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SelectCompanyRoute: typeof SelectCompanyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/floor': {
      id: '/_authenticated/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof AuthenticatedFloorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/': {
      id: '/_authenticated/strategy/'
      path: '/strategy'
      fullPath: '/strategy/'
      preLoaderRoute: typeof AuthenticatedStrategyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/': {
      id: '/_authenticated/oms/'
      path: '/oms'
      fullPath: '/oms/'
      preLoaderRoute: typeof AuthenticatedOmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting/': {
      id: '/_authenticated/meeting/'
      path: '/meeting'
      fullPath: '/meeting/'
      preLoaderRoute: typeof AuthenticatedMeetingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/': {
      id: '/_authenticated/commercial/'
      path: '/commercial'
      fullPath: '/commercial/'
      preLoaderRoute: typeof AuthenticatedCommercialIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/': {
      id: '/_authenticated/actions/'
      path: '/'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthenticatedActionsIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/strategy/waterfall': {
      id: '/_authenticated/strategy/waterfall'
      path: '/strategy/waterfall'
      fullPath: '/strategy/waterfall'
      preLoaderRoute: typeof AuthenticatedStrategyWaterfallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/restructuring': {
      id: '/_authenticated/strategy/restructuring'
      path: '/strategy/restructuring'
      fullPath: '/strategy/restructuring'
      preLoaderRoute: typeof AuthenticatedStrategyRestructuringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/initiatives': {
      id: '/_authenticated/strategy/initiatives'
      path: '/strategy/initiatives'
      fullPath: '/strategy/initiatives'
      preLoaderRoute: typeof AuthenticatedStrategyInitiativesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/hoshin': {
      id: '/_authenticated/strategy/hoshin'
      path: '/strategy/hoshin'
      fullPath: '/strategy/hoshin'
      preLoaderRoute: typeof AuthenticatedStrategyHoshinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/consolidation': {
      id: '/_authenticated/strategy/consolidation'
      path: '/strategy/consolidation'
      fullPath: '/strategy/consolidation'
      preLoaderRoute: typeof AuthenticatedStrategyConsolidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy/capex': {
      id: '/_authenticated/strategy/capex'
      path: '/strategy/capex'
      fullPath: '/strategy/capex'
      preLoaderRoute: typeof AuthenticatedStrategyCapexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/owner': {
      id: '/_authenticated/report/owner'
      path: '/report/owner'
      fullPath: '/report/owner'
      preLoaderRoute: typeof AuthenticatedReportOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/industrial-strategy': {
      id: '/_authenticated/report/industrial-strategy'
      path: '/report/industrial-strategy'
      fullPath: '/report/industrial-strategy'
      preLoaderRoute: typeof AuthenticatedReportIndustrialStrategyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/enterprise-network': {
      id: '/_authenticated/report/enterprise-network'
      path: '/report/enterprise-network'
      fullPath: '/report/enterprise-network'
      preLoaderRoute: typeof AuthenticatedReportEnterpriseNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/business-health': {
      id: '/_authenticated/report/business-health'
      path: '/report/business-health'
      fullPath: '/report/business-health'
      preLoaderRoute: typeof AuthenticatedReportBusinessHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/board': {
      id: '/_authenticated/report/board'
      path: '/report/board'
      fullPath: '/report/board'
      preLoaderRoute: typeof AuthenticatedReportBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/skills': {
      id: '/_authenticated/people/skills'
      path: '/people/skills'
      fullPath: '/people/skills'
      preLoaderRoute: typeof AuthenticatedPeopleSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/roles': {
      id: '/_authenticated/people/roles'
      path: '/people/roles'
      fullPath: '/people/roles'
      preLoaderRoute: typeof AuthenticatedPeopleRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/org-chart': {
      id: '/_authenticated/people/org-chart'
      path: '/people/org-chart'
      fullPath: '/people/org-chart'
      preLoaderRoute: typeof AuthenticatedPeopleOrgChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/matrix': {
      id: '/_authenticated/people/matrix'
      path: '/people/matrix'
      fullPath: '/people/matrix'
      preLoaderRoute: typeof AuthenticatedPeopleMatrixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/leadership': {
      id: '/_authenticated/people/leadership'
      path: '/people/leadership'
      fullPath: '/people/leadership'
      preLoaderRoute: typeof AuthenticatedPeopleLeadershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/import': {
      id: '/_authenticated/people/import'
      path: '/people/import'
      fullPath: '/people/import'
      preLoaderRoute: typeof AuthenticatedPeopleImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/gaps': {
      id: '/_authenticated/people/gaps'
      path: '/people/gaps'
      fullPath: '/people/gaps'
      preLoaderRoute: typeof AuthenticatedPeopleGapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/engagement': {
      id: '/_authenticated/people/engagement'
      path: '/people/engagement'
      fullPath: '/people/engagement'
      preLoaderRoute: typeof AuthenticatedPeopleEngagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/employees': {
      id: '/_authenticated/people/employees'
      path: '/people/employees'
      fullPath: '/people/employees'
      preLoaderRoute: typeof AuthenticatedPeopleEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/development': {
      id: '/_authenticated/people/development'
      path: '/people/development'
      fullPath: '/people/development'
      preLoaderRoute: typeof AuthenticatedPeopleDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/certifications': {
      id: '/_authenticated/people/certifications'
      path: '/people/certifications'
      fullPath: '/people/certifications'
      preLoaderRoute: typeof AuthenticatedPeopleCertificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/vsm': {
      id: '/_authenticated/oms/vsm'
      path: '/oms/vsm'
      fullPath: '/oms/vsm'
      preLoaderRoute: typeof AuthenticatedOmsVsmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/supply-chain': {
      id: '/_authenticated/oms/supply-chain'
      path: '/oms/supply-chain'
      fullPath: '/oms/supply-chain'
      preLoaderRoute: typeof AuthenticatedOmsSupplyChainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/standard-work': {
      id: '/_authenticated/oms/standard-work'
      path: '/oms/standard-work'
      fullPath: '/oms/standard-work'
      preLoaderRoute: typeof AuthenticatedOmsStandardWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/siop': {
      id: '/_authenticated/oms/siop'
      path: '/oms/siop'
      fullPath: '/oms/siop'
      preLoaderRoute: typeof AuthenticatedOmsSiopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/sic': {
      id: '/_authenticated/oms/sic'
      path: '/oms/sic'
      fullPath: '/oms/sic'
      preLoaderRoute: typeof AuthenticatedOmsSicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/shopfloor': {
      id: '/_authenticated/oms/shopfloor'
      path: '/oms/shopfloor'
      fullPath: '/oms/shopfloor'
      preLoaderRoute: typeof AuthenticatedOmsShopfloorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/scheduling': {
      id: '/_authenticated/oms/scheduling'
      path: '/oms/scheduling'
      fullPath: '/oms/scheduling'
      preLoaderRoute: typeof AuthenticatedOmsSchedulingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/risk': {
      id: '/_authenticated/oms/risk'
      path: '/oms/risk'
      fullPath: '/oms/risk'
      preLoaderRoute: typeof AuthenticatedOmsRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/quality': {
      id: '/_authenticated/oms/quality'
      path: '/oms/quality'
      fullPath: '/oms/quality'
      preLoaderRoute: typeof AuthenticatedOmsQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/npi': {
      id: '/_authenticated/oms/npi'
      path: '/oms/npi'
      fullPath: '/oms/npi'
      preLoaderRoute: typeof AuthenticatedOmsNpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/kpis': {
      id: '/_authenticated/oms/kpis'
      path: '/oms/kpis'
      fullPath: '/oms/kpis'
      preLoaderRoute: typeof AuthenticatedOmsKpisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/industrialization': {
      id: '/_authenticated/oms/industrialization'
      path: '/oms/industrialization'
      fullPath: '/oms/industrialization'
      preLoaderRoute: typeof AuthenticatedOmsIndustrializationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/end-of-life': {
      id: '/_authenticated/oms/end-of-life'
      path: '/oms/end-of-life'
      fullPath: '/oms/end-of-life'
      preLoaderRoute: typeof AuthenticatedOmsEndOfLifeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/daily': {
      id: '/_authenticated/oms/daily'
      path: '/oms/daily'
      fullPath: '/oms/daily'
      preLoaderRoute: typeof AuthenticatedOmsDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/critical-path': {
      id: '/_authenticated/oms/critical-path'
      path: '/oms/critical-path'
      fullPath: '/oms/critical-path'
      preLoaderRoute: typeof AuthenticatedOmsCriticalPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oms/compliance': {
      id: '/_authenticated/oms/compliance'
      path: '/oms/compliance'
      fullPath: '/oms/compliance'
      preLoaderRoute: typeof AuthenticatedOmsComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting/weekly': {
      id: '/_authenticated/meeting/weekly'
      path: '/meeting/weekly'
      fullPath: '/meeting/weekly'
      preLoaderRoute: typeof AuthenticatedMeetingWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/voc': {
      id: '/_authenticated/commercial/voc'
      path: '/commercial/voc'
      fullPath: '/commercial/voc'
      preLoaderRoute: typeof AuthenticatedCommercialVocRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/stakeholders': {
      id: '/_authenticated/commercial/stakeholders'
      path: '/commercial/stakeholders'
      fullPath: '/commercial/stakeholders'
      preLoaderRoute: typeof AuthenticatedCommercialStakeholdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/review': {
      id: '/_authenticated/commercial/review'
      path: '/commercial/review'
      fullPath: '/commercial/review'
      preLoaderRoute: typeof AuthenticatedCommercialReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/plan': {
      id: '/_authenticated/commercial/plan'
      path: '/commercial/plan'
      fullPath: '/commercial/plan'
      preLoaderRoute: typeof AuthenticatedCommercialPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/opportunities': {
      id: '/_authenticated/commercial/opportunities'
      path: '/commercial/opportunities'
      fullPath: '/commercial/opportunities'
      preLoaderRoute: typeof AuthenticatedCommercialOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/contracts': {
      id: '/_authenticated/commercial/contracts'
      path: '/commercial/contracts'
      fullPath: '/commercial/contracts'
      preLoaderRoute: typeof AuthenticatedCommercialContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/team-room/': {
      id: '/_authenticated/report/team-room/'
      path: '/report/team-room'
      fullPath: '/report/team-room/'
      preLoaderRoute: typeof AuthenticatedReportTeamRoomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/accounts/': {
      id: '/_authenticated/commercial/accounts/'
      path: '/commercial/accounts'
      fullPath: '/commercial/accounts/'
      preLoaderRoute: typeof AuthenticatedCommercialAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/problem-solver/': {
      id: '/_authenticated/actions/problem-solver/'
      path: '/problem-solver'
      fullPath: '/actions/problem-solver/'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/playbook/': {
      id: '/_authenticated/actions/playbook/'
      path: '/playbook'
      fullPath: '/actions/playbook/'
      preLoaderRoute: typeof AuthenticatedActionsPlaybookIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/': {
      id: '/_authenticated/actions/calculators/'
      path: '/calculators'
      fullPath: '/actions/calculators/'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/report/team-room/$threadId': {
      id: '/_authenticated/report/team-room/$threadId'
      path: '/report/team-room/$threadId'
      fullPath: '/report/team-room/$threadId'
      preLoaderRoute: typeof AuthenticatedReportTeamRoomThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/employees/$id': {
      id: '/_authenticated/people/employees/$id'
      path: '/$id'
      fullPath: '/people/employees/$id'
      preLoaderRoute: typeof AuthenticatedPeopleEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedPeopleEmployeesRoute
    }
    '/_authenticated/oms/pillars/$pillarKey': {
      id: '/_authenticated/oms/pillars/$pillarKey'
      path: '/oms/pillars/$pillarKey'
      fullPath: '/oms/pillars/$pillarKey'
      preLoaderRoute: typeof AuthenticatedOmsPillarsPillarKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/accounts/$id': {
      id: '/_authenticated/commercial/accounts/$id'
      path: '/commercial/accounts/$id'
      fullPath: '/commercial/accounts/$id'
      preLoaderRoute: typeof AuthenticatedCommercialAccountsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actions/problem-solver/mro': {
      id: '/_authenticated/actions/problem-solver/mro'
      path: '/problem-solver/mro'
      fullPath: '/actions/problem-solver/mro'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverMroRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/five-whys': {
      id: '/_authenticated/actions/problem-solver/five-whys'
      path: '/problem-solver/five-whys'
      fullPath: '/actions/problem-solver/five-whys'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverFiveWhysRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/fishbone': {
      id: '/_authenticated/actions/problem-solver/fishbone'
      path: '/problem-solver/fishbone'
      fullPath: '/actions/problem-solver/fishbone'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverFishboneRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/eight-d': {
      id: '/_authenticated/actions/problem-solver/eight-d'
      path: '/problem-solver/eight-d'
      fullPath: '/actions/problem-solver/eight-d'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverEightDRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/dmaic': {
      id: '/_authenticated/actions/problem-solver/dmaic'
      path: '/problem-solver/dmaic'
      fullPath: '/actions/problem-solver/dmaic'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverDmaicRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/a3': {
      id: '/_authenticated/actions/problem-solver/a3'
      path: '/problem-solver/a3'
      fullPath: '/actions/problem-solver/a3'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverA3RouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/playbook/$id': {
      id: '/_authenticated/actions/playbook/$id'
      path: '/playbook/$id'
      fullPath: '/actions/playbook/$id'
      preLoaderRoute: typeof AuthenticatedActionsPlaybookIdRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/takt': {
      id: '/_authenticated/actions/calculators/takt'
      path: '/calculators/takt'
      fullPath: '/actions/calculators/takt'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsTaktRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/oee': {
      id: '/_authenticated/actions/calculators/oee'
      path: '/calculators/oee'
      fullPath: '/actions/calculators/oee'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsOeeRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/downtime': {
      id: '/_authenticated/actions/calculators/downtime'
      path: '/calculators/downtime'
      fullPath: '/actions/calculators/downtime'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsDowntimeRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/copq': {
      id: '/_authenticated/actions/calculators/copq'
      path: '/calculators/copq'
      fullPath: '/actions/calculators/copq'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsCopqRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/calculators/changeover': {
      id: '/_authenticated/actions/calculators/changeover'
      path: '/calculators/changeover'
      fullPath: '/actions/calculators/changeover'
      preLoaderRoute: typeof AuthenticatedActionsCalculatorsChangeoverRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/': {
      id: '/_authenticated/actions/problem-solver/toolkit/'
      path: '/problem-solver/toolkit'
      fullPath: '/actions/problem-solver/toolkit/'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/flows/': {
      id: '/_authenticated/actions/problem-solver/flows/'
      path: '/problem-solver/flows'
      fullPath: '/actions/problem-solver/flows/'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/toc': {
      id: '/_authenticated/actions/problem-solver/toolkit/toc'
      path: '/problem-solver/toolkit/toc'
      fullPath: '/actions/problem-solver/toolkit/toc'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitTocRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/journey': {
      id: '/_authenticated/actions/problem-solver/toolkit/journey'
      path: '/problem-solver/toolkit/journey'
      fullPath: '/actions/problem-solver/toolkit/journey'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitJourneyRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/ibp': {
      id: '/_authenticated/actions/problem-solver/toolkit/ibp'
      path: '/problem-solver/toolkit/ibp'
      fullPath: '/actions/problem-solver/toolkit/ibp'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitIbpRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/hoshin': {
      id: '/_authenticated/actions/problem-solver/toolkit/hoshin'
      path: '/problem-solver/toolkit/hoshin'
      fullPath: '/actions/problem-solver/toolkit/hoshin'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitHoshinRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/toolkit/cld': {
      id: '/_authenticated/actions/problem-solver/toolkit/cld'
      path: '/problem-solver/toolkit/cld'
      fullPath: '/actions/problem-solver/toolkit/cld'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverToolkitCldRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
    '/_authenticated/actions/problem-solver/flows/$id': {
      id: '/_authenticated/actions/problem-solver/flows/$id'
      path: '/problem-solver/flows/$id'
      fullPath: '/actions/problem-solver/flows/$id'
      preLoaderRoute: typeof AuthenticatedActionsProblemSolverFlowsIdRouteImport
      parentRoute: typeof AuthenticatedActionsRouteRoute
    }
  }
}

interface AuthenticatedActionsRouteRouteChildren {
  AuthenticatedActionsIndexRoute: typeof AuthenticatedActionsIndexRoute
  AuthenticatedActionsCalculatorsChangeoverRoute: typeof AuthenticatedActionsCalculatorsChangeoverRoute
  AuthenticatedActionsCalculatorsCopqRoute: typeof AuthenticatedActionsCalculatorsCopqRoute
  AuthenticatedActionsCalculatorsDowntimeRoute: typeof AuthenticatedActionsCalculatorsDowntimeRoute
  AuthenticatedActionsCalculatorsOeeRoute: typeof AuthenticatedActionsCalculatorsOeeRoute
  AuthenticatedActionsCalculatorsTaktRoute: typeof AuthenticatedActionsCalculatorsTaktRoute
  AuthenticatedActionsPlaybookIdRoute: typeof AuthenticatedActionsPlaybookIdRoute
  AuthenticatedActionsProblemSolverA3Route: typeof AuthenticatedActionsProblemSolverA3Route
  AuthenticatedActionsProblemSolverDmaicRoute: typeof AuthenticatedActionsProblemSolverDmaicRoute
  AuthenticatedActionsProblemSolverEightDRoute: typeof AuthenticatedActionsProblemSolverEightDRoute
  AuthenticatedActionsProblemSolverFishboneRoute: typeof AuthenticatedActionsProblemSolverFishboneRoute
  AuthenticatedActionsProblemSolverFiveWhysRoute: typeof AuthenticatedActionsProblemSolverFiveWhysRoute
  AuthenticatedActionsProblemSolverMroRoute: typeof AuthenticatedActionsProblemSolverMroRoute
  AuthenticatedActionsCalculatorsIndexRoute: typeof AuthenticatedActionsCalculatorsIndexRoute
  AuthenticatedActionsPlaybookIndexRoute: typeof AuthenticatedActionsPlaybookIndexRoute
  AuthenticatedActionsProblemSolverIndexRoute: typeof AuthenticatedActionsProblemSolverIndexRoute
  AuthenticatedActionsProblemSolverFlowsIdRoute: typeof AuthenticatedActionsProblemSolverFlowsIdRoute
  AuthenticatedActionsProblemSolverToolkitCldRoute: typeof AuthenticatedActionsProblemSolverToolkitCldRoute
  AuthenticatedActionsProblemSolverToolkitHoshinRoute: typeof AuthenticatedActionsProblemSolverToolkitHoshinRoute
  AuthenticatedActionsProblemSolverToolkitIbpRoute: typeof AuthenticatedActionsProblemSolverToolkitIbpRoute
  AuthenticatedActionsProblemSolverToolkitJourneyRoute: typeof AuthenticatedActionsProblemSolverToolkitJourneyRoute
  AuthenticatedActionsProblemSolverToolkitTocRoute: typeof AuthenticatedActionsProblemSolverToolkitTocRoute
  AuthenticatedActionsProblemSolverFlowsIndexRoute: typeof AuthenticatedActionsProblemSolverFlowsIndexRoute
  AuthenticatedActionsProblemSolverToolkitIndexRoute: typeof AuthenticatedActionsProblemSolverToolkitIndexRoute
}

const AuthenticatedActionsRouteRouteChildren: AuthenticatedActionsRouteRouteChildren =
  {
    AuthenticatedActionsIndexRoute: AuthenticatedActionsIndexRoute,
    AuthenticatedActionsCalculatorsChangeoverRoute:
      AuthenticatedActionsCalculatorsChangeoverRoute,
    AuthenticatedActionsCalculatorsCopqRoute:
      AuthenticatedActionsCalculatorsCopqRoute,
    AuthenticatedActionsCalculatorsDowntimeRoute:
      AuthenticatedActionsCalculatorsDowntimeRoute,
    AuthenticatedActionsCalculatorsOeeRoute:
      AuthenticatedActionsCalculatorsOeeRoute,
    AuthenticatedActionsCalculatorsTaktRoute:
      AuthenticatedActionsCalculatorsTaktRoute,
    AuthenticatedActionsPlaybookIdRoute: AuthenticatedActionsPlaybookIdRoute,
    AuthenticatedActionsProblemSolverA3Route:
      AuthenticatedActionsProblemSolverA3Route,
    AuthenticatedActionsProblemSolverDmaicRoute:
      AuthenticatedActionsProblemSolverDmaicRoute,
    AuthenticatedActionsProblemSolverEightDRoute:
      AuthenticatedActionsProblemSolverEightDRoute,
    AuthenticatedActionsProblemSolverFishboneRoute:
      AuthenticatedActionsProblemSolverFishboneRoute,
    AuthenticatedActionsProblemSolverFiveWhysRoute:
      AuthenticatedActionsProblemSolverFiveWhysRoute,
    AuthenticatedActionsProblemSolverMroRoute:
      AuthenticatedActionsProblemSolverMroRoute,
    AuthenticatedActionsCalculatorsIndexRoute:
      AuthenticatedActionsCalculatorsIndexRoute,
    AuthenticatedActionsPlaybookIndexRoute:
      AuthenticatedActionsPlaybookIndexRoute,
    AuthenticatedActionsProblemSolverIndexRoute:
      AuthenticatedActionsProblemSolverIndexRoute,
    AuthenticatedActionsProblemSolverFlowsIdRoute:
      AuthenticatedActionsProblemSolverFlowsIdRoute,
    AuthenticatedActionsProblemSolverToolkitCldRoute:
      AuthenticatedActionsProblemSolverToolkitCldRoute,
    AuthenticatedActionsProblemSolverToolkitHoshinRoute:
      AuthenticatedActionsProblemSolverToolkitHoshinRoute,
    AuthenticatedActionsProblemSolverToolkitIbpRoute:
      AuthenticatedActionsProblemSolverToolkitIbpRoute,
    AuthenticatedActionsProblemSolverToolkitJourneyRoute:
      AuthenticatedActionsProblemSolverToolkitJourneyRoute,
    AuthenticatedActionsProblemSolverToolkitTocRoute:
      AuthenticatedActionsProblemSolverToolkitTocRoute,
    AuthenticatedActionsProblemSolverFlowsIndexRoute:
      AuthenticatedActionsProblemSolverFlowsIndexRoute,
    AuthenticatedActionsProblemSolverToolkitIndexRoute:
      AuthenticatedActionsProblemSolverToolkitIndexRoute,
  }

const AuthenticatedActionsRouteRouteWithChildren =
  AuthenticatedActionsRouteRoute._addFileChildren(
    AuthenticatedActionsRouteRouteChildren,
  )

interface AuthenticatedPeopleEmployeesRouteChildren {
  AuthenticatedPeopleEmployeesIdRoute: typeof AuthenticatedPeopleEmployeesIdRoute
}

const AuthenticatedPeopleEmployeesRouteChildren: AuthenticatedPeopleEmployeesRouteChildren =
  {
    AuthenticatedPeopleEmployeesIdRoute: AuthenticatedPeopleEmployeesIdRoute,
  }

const AuthenticatedPeopleEmployeesRouteWithChildren =
  AuthenticatedPeopleEmployeesRoute._addFileChildren(
    AuthenticatedPeopleEmployeesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionsRouteRoute: typeof AuthenticatedActionsRouteRouteWithChildren
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedFloorRoute: typeof AuthenticatedFloorRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedCommercialContractsRoute: typeof AuthenticatedCommercialContractsRoute
  AuthenticatedCommercialOpportunitiesRoute: typeof AuthenticatedCommercialOpportunitiesRoute
  AuthenticatedCommercialPlanRoute: typeof AuthenticatedCommercialPlanRoute
  AuthenticatedCommercialReviewRoute: typeof AuthenticatedCommercialReviewRoute
  AuthenticatedCommercialStakeholdersRoute: typeof AuthenticatedCommercialStakeholdersRoute
  AuthenticatedCommercialVocRoute: typeof AuthenticatedCommercialVocRoute
  AuthenticatedMeetingWeeklyRoute: typeof AuthenticatedMeetingWeeklyRoute
  AuthenticatedOmsComplianceRoute: typeof AuthenticatedOmsComplianceRoute
  AuthenticatedOmsCriticalPathRoute: typeof AuthenticatedOmsCriticalPathRoute
  AuthenticatedOmsDailyRoute: typeof AuthenticatedOmsDailyRoute
  AuthenticatedOmsEndOfLifeRoute: typeof AuthenticatedOmsEndOfLifeRoute
  AuthenticatedOmsIndustrializationRoute: typeof AuthenticatedOmsIndustrializationRoute
  AuthenticatedOmsKpisRoute: typeof AuthenticatedOmsKpisRoute
  AuthenticatedOmsNpiRoute: typeof AuthenticatedOmsNpiRoute
  AuthenticatedOmsQualityRoute: typeof AuthenticatedOmsQualityRoute
  AuthenticatedOmsRiskRoute: typeof AuthenticatedOmsRiskRoute
  AuthenticatedOmsSchedulingRoute: typeof AuthenticatedOmsSchedulingRoute
  AuthenticatedOmsShopfloorRoute: typeof AuthenticatedOmsShopfloorRoute
  AuthenticatedOmsSicRoute: typeof AuthenticatedOmsSicRoute
  AuthenticatedOmsSiopRoute: typeof AuthenticatedOmsSiopRoute
  AuthenticatedOmsStandardWorkRoute: typeof AuthenticatedOmsStandardWorkRoute
  AuthenticatedOmsSupplyChainRoute: typeof AuthenticatedOmsSupplyChainRoute
  AuthenticatedOmsVsmRoute: typeof AuthenticatedOmsVsmRoute
  AuthenticatedPeopleCertificationsRoute: typeof AuthenticatedPeopleCertificationsRoute
  AuthenticatedPeopleDevelopmentRoute: typeof AuthenticatedPeopleDevelopmentRoute
  AuthenticatedPeopleEmployeesRoute: typeof AuthenticatedPeopleEmployeesRouteWithChildren
  AuthenticatedPeopleEngagementRoute: typeof AuthenticatedPeopleEngagementRoute
  AuthenticatedPeopleGapsRoute: typeof AuthenticatedPeopleGapsRoute
  AuthenticatedPeopleImportRoute: typeof AuthenticatedPeopleImportRoute
  AuthenticatedPeopleLeadershipRoute: typeof AuthenticatedPeopleLeadershipRoute
  AuthenticatedPeopleMatrixRoute: typeof AuthenticatedPeopleMatrixRoute
  AuthenticatedPeopleOrgChartRoute: typeof AuthenticatedPeopleOrgChartRoute
  AuthenticatedPeopleRolesRoute: typeof AuthenticatedPeopleRolesRoute
  AuthenticatedPeopleSkillsRoute: typeof AuthenticatedPeopleSkillsRoute
  AuthenticatedReportBoardRoute: typeof AuthenticatedReportBoardRoute
  AuthenticatedReportBusinessHealthRoute: typeof AuthenticatedReportBusinessHealthRoute
  AuthenticatedReportEnterpriseNetworkRoute: typeof AuthenticatedReportEnterpriseNetworkRoute
  AuthenticatedReportIndustrialStrategyRoute: typeof AuthenticatedReportIndustrialStrategyRoute
  AuthenticatedReportOwnerRoute: typeof AuthenticatedReportOwnerRoute
  AuthenticatedStrategyCapexRoute: typeof AuthenticatedStrategyCapexRoute
  AuthenticatedStrategyConsolidationRoute: typeof AuthenticatedStrategyConsolidationRoute
  AuthenticatedStrategyHoshinRoute: typeof AuthenticatedStrategyHoshinRoute
  AuthenticatedStrategyInitiativesRoute: typeof AuthenticatedStrategyInitiativesRoute
  AuthenticatedStrategyRestructuringRoute: typeof AuthenticatedStrategyRestructuringRoute
  AuthenticatedStrategyWaterfallRoute: typeof AuthenticatedStrategyWaterfallRoute
  AuthenticatedCommercialIndexRoute: typeof AuthenticatedCommercialIndexRoute
  AuthenticatedMeetingIndexRoute: typeof AuthenticatedMeetingIndexRoute
  AuthenticatedOmsIndexRoute: typeof AuthenticatedOmsIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
  AuthenticatedStrategyIndexRoute: typeof AuthenticatedStrategyIndexRoute
  AuthenticatedCommercialAccountsIdRoute: typeof AuthenticatedCommercialAccountsIdRoute
  AuthenticatedOmsPillarsPillarKeyRoute: typeof AuthenticatedOmsPillarsPillarKeyRoute
  AuthenticatedReportTeamRoomThreadIdRoute: typeof AuthenticatedReportTeamRoomThreadIdRoute
  AuthenticatedCommercialAccountsIndexRoute: typeof AuthenticatedCommercialAccountsIndexRoute
  AuthenticatedReportTeamRoomIndexRoute: typeof AuthenticatedReportTeamRoomIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionsRouteRoute: AuthenticatedActionsRouteRouteWithChildren,
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedFloorRoute: AuthenticatedFloorRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedCommercialContractsRoute: AuthenticatedCommercialContractsRoute,
  AuthenticatedCommercialOpportunitiesRoute:
    AuthenticatedCommercialOpportunitiesRoute,
  AuthenticatedCommercialPlanRoute: AuthenticatedCommercialPlanRoute,
  AuthenticatedCommercialReviewRoute: AuthenticatedCommercialReviewRoute,
  AuthenticatedCommercialStakeholdersRoute:
    AuthenticatedCommercialStakeholdersRoute,
  AuthenticatedCommercialVocRoute: AuthenticatedCommercialVocRoute,
  AuthenticatedMeetingWeeklyRoute: AuthenticatedMeetingWeeklyRoute,
  AuthenticatedOmsComplianceRoute: AuthenticatedOmsComplianceRoute,
  AuthenticatedOmsCriticalPathRoute: AuthenticatedOmsCriticalPathRoute,
  AuthenticatedOmsDailyRoute: AuthenticatedOmsDailyRoute,
  AuthenticatedOmsEndOfLifeRoute: AuthenticatedOmsEndOfLifeRoute,
  AuthenticatedOmsIndustrializationRoute:
    AuthenticatedOmsIndustrializationRoute,
  AuthenticatedOmsKpisRoute: AuthenticatedOmsKpisRoute,
  AuthenticatedOmsNpiRoute: AuthenticatedOmsNpiRoute,
  AuthenticatedOmsQualityRoute: AuthenticatedOmsQualityRoute,
  AuthenticatedOmsRiskRoute: AuthenticatedOmsRiskRoute,
  AuthenticatedOmsSchedulingRoute: AuthenticatedOmsSchedulingRoute,
  AuthenticatedOmsShopfloorRoute: AuthenticatedOmsShopfloorRoute,
  AuthenticatedOmsSicRoute: AuthenticatedOmsSicRoute,
  AuthenticatedOmsSiopRoute: AuthenticatedOmsSiopRoute,
  AuthenticatedOmsStandardWorkRoute: AuthenticatedOmsStandardWorkRoute,
  AuthenticatedOmsSupplyChainRoute: AuthenticatedOmsSupplyChainRoute,
  AuthenticatedOmsVsmRoute: AuthenticatedOmsVsmRoute,
  AuthenticatedPeopleCertificationsRoute:
    AuthenticatedPeopleCertificationsRoute,
  AuthenticatedPeopleDevelopmentRoute: AuthenticatedPeopleDevelopmentRoute,
  AuthenticatedPeopleEmployeesRoute:
    AuthenticatedPeopleEmployeesRouteWithChildren,
  AuthenticatedPeopleEngagementRoute: AuthenticatedPeopleEngagementRoute,
  AuthenticatedPeopleGapsRoute: AuthenticatedPeopleGapsRoute,
  AuthenticatedPeopleImportRoute: AuthenticatedPeopleImportRoute,
  AuthenticatedPeopleLeadershipRoute: AuthenticatedPeopleLeadershipRoute,
  AuthenticatedPeopleMatrixRoute: AuthenticatedPeopleMatrixRoute,
  AuthenticatedPeopleOrgChartRoute: AuthenticatedPeopleOrgChartRoute,
  AuthenticatedPeopleRolesRoute: AuthenticatedPeopleRolesRoute,
  AuthenticatedPeopleSkillsRoute: AuthenticatedPeopleSkillsRoute,
  AuthenticatedReportBoardRoute: AuthenticatedReportBoardRoute,
  AuthenticatedReportBusinessHealthRoute:
    AuthenticatedReportBusinessHealthRoute,
  AuthenticatedReportEnterpriseNetworkRoute:
    AuthenticatedReportEnterpriseNetworkRoute,
  AuthenticatedReportIndustrialStrategyRoute:
    AuthenticatedReportIndustrialStrategyRoute,
  AuthenticatedReportOwnerRoute: AuthenticatedReportOwnerRoute,
  AuthenticatedStrategyCapexRoute: AuthenticatedStrategyCapexRoute,
  AuthenticatedStrategyConsolidationRoute:
    AuthenticatedStrategyConsolidationRoute,
  AuthenticatedStrategyHoshinRoute: AuthenticatedStrategyHoshinRoute,
  AuthenticatedStrategyInitiativesRoute: AuthenticatedStrategyInitiativesRoute,
  AuthenticatedStrategyRestructuringRoute:
    AuthenticatedStrategyRestructuringRoute,
  AuthenticatedStrategyWaterfallRoute: AuthenticatedStrategyWaterfallRoute,
  AuthenticatedCommercialIndexRoute: AuthenticatedCommercialIndexRoute,
  AuthenticatedMeetingIndexRoute: AuthenticatedMeetingIndexRoute,
  AuthenticatedOmsIndexRoute: AuthenticatedOmsIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
  AuthenticatedStrategyIndexRoute: AuthenticatedStrategyIndexRoute,
  AuthenticatedCommercialAccountsIdRoute:
    AuthenticatedCommercialAccountsIdRoute,
  AuthenticatedOmsPillarsPillarKeyRoute: AuthenticatedOmsPillarsPillarKeyRoute,
  AuthenticatedReportTeamRoomThreadIdRoute:
    AuthenticatedReportTeamRoomThreadIdRoute,
  AuthenticatedCommercialAccountsIndexRoute:
    AuthenticatedCommercialAccountsIndexRoute,
  AuthenticatedReportTeamRoomIndexRoute: AuthenticatedReportTeamRoomIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SelectCompanyRoute: SelectCompanyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
