// Owner metric catalogue — the pickable database of owner-level metrics.
// Pure reference data (same idea as kpi-library.ts): the picker dialog, the
// tile computation and the saved templates all read from this one list.
import type { OwnerSectionId, TileUnit } from "@/lib/owner-dashboard";

export type OwnerMetricSource = "auto" | "kpi" | "manual";
export type OwnerPackId = "essentials" | "cash" | "growth" | "bank";

export const OWNER_PACKS: { id: OwnerPackId; name: string; blurb: string }[] = [
  { id: "essentials", name: "Owner essentials", blurb: "The default one-page board." },
  { id: "cash", name: "Cash focused", blurb: "Cash, working capital and collection." },
  { id: "growth", name: "Growth focused", blurb: "Backlog, pipeline, win rate and mix." },
  { id: "bank", name: "Bank / lender pack", blurb: "Leverage, covenant and cash quality." },
];

export const OWNER_SOURCES: { id: OwnerMetricSource; name: string; blurb: string }[] = [
  { id: "auto", name: "Auto", blurb: "Calculated from data already in the app." },
  { id: "kpi", name: "KPI library", blurb: "Reads the matching KPI on the KPIs page." },
  { id: "manual", name: "Manual entry", blurb: "You type it in with the monthly financials." },
];

export type OwnerMetricDef = {
  id: string;
  section: OwnerSectionId;
  label: string;
  definition: string;
  unit: TileUnit;
  higherIsBetter: boolean;
  source: OwnerMetricSource;
  /** KPI library keys this metric can bind to (source = "kpi"). */
  kpiKeys?: string[];
  /** Fallback name match when no library key is set on the company KPI. */
  kpiMatch?: string;
  defaultTarget?: number | null;
  packs: OwnerPackId[];
};

export const OWNER_METRICS: OwnerMetricDef[] = [
  // ── Financial ────────────────────────────────────────────────────────
  { id: "fin.revenue", section: "financial", label: "Revenue (month)", definition: "Actual revenue for the latest closed month against budget.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "growth", "bank"] },
  { id: "fin.revenue_py", section: "financial", label: "Revenue vs last year", definition: "Same month a year ago as the target line.", unit: "money", higherIsBetter: true, source: "auto", packs: ["growth"] },
  { id: "fin.revenue_ytd", section: "financial", label: "Revenue year to date", definition: "Calendar year to date revenue against year to date budget.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "fin.gross_profit", section: "financial", label: "Gross profit (month)", definition: "Revenue less cost of goods sold.", unit: "money", higherIsBetter: true, source: "auto", packs: [] },
  { id: "fin.gross_margin", section: "financial", label: "Gross margin", definition: "(Revenue − COGS) / Revenue.", unit: "pct", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "fin.ebitda", section: "financial", label: "EBITDA (month)", definition: "Month EBITDA against budget.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "fin.ebitda_margin", section: "financial", label: "EBITDA margin", definition: "EBITDA as a share of revenue.", unit: "pct", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "fin.ebitda_ytd", section: "financial", label: "EBITDA year to date", definition: "Calendar year to date EBITDA against year to date budget.", unit: "money", higherIsBetter: true, source: "auto", packs: ["bank"] },
  { id: "fin.opex", section: "financial", label: "Operating expense", definition: "Month operating expense.", unit: "money", higherIsBetter: false, source: "auto", packs: [] },
  { id: "fin.opex_pct", section: "financial", label: "Opex as % of revenue", definition: "Operating expense divided by revenue.", unit: "pct", higherIsBetter: false, source: "auto", packs: [] },
  { id: "fin.cash", section: "financial", label: "Cash on hand", definition: "Closing cash balance for the month.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "cash", "bank"] },
  { id: "fin.ocf", section: "financial", label: "Operating cash flow", definition: "Cash generated by operations in the month.", unit: "money", higherIsBetter: true, source: "auto", packs: ["cash", "bank"] },
  { id: "fin.fcf", section: "financial", label: "Free cash flow (month)", definition: "Operating cash flow after capital spend.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "cash", "bank"] },
  { id: "fin.fcf_ltm", section: "financial", label: "Free cash flow (LTM)", definition: "Free cash flow over the last twelve months.", unit: "money", higherIsBetter: true, source: "auto", packs: ["cash", "bank"] },
  { id: "fin.cash_runway", section: "financial", label: "Cash runway", definition: "Cash divided by average monthly cash burn — blank when cash generative.", unit: "num", higherIsBetter: true, source: "auto", packs: ["cash"] },
  { id: "fin.budget_variance", section: "financial", label: "Revenue vs budget", definition: "Month revenue as a percentage of budget.", unit: "pct", higherIsBetter: true, defaultTarget: 100, source: "auto", packs: [] },

  // ── Commercial ───────────────────────────────────────────────────────
  { id: "com.backlog", section: "commercial", label: "Booked backlog (12m)", definition: "Confirmed orders on the books for the next twelve months.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "growth", "bank"] },
  { id: "com.pipeline", section: "commercial", label: "Weighted pipeline", definition: "Open opportunity value weighted by probability.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "growth"] },
  { id: "com.pipeline_gross", section: "commercial", label: "Open pipeline (unweighted)", definition: "Total value of all open opportunities.", unit: "money", higherIsBetter: true, source: "auto", packs: ["growth"] },
  { id: "com.coverage", section: "commercial", label: "Coverage vs target", definition: "Backlog plus weighted pipeline against the twelve-month target.", unit: "pct", higherIsBetter: true, defaultTarget: 100, source: "auto", packs: ["essentials", "growth"] },
  { id: "com.win_rate", section: "commercial", label: "Win rate", definition: "Won opportunities divided by won plus lost.", unit: "pct", higherIsBetter: true, defaultTarget: 40, source: "auto", packs: ["growth"] },
  { id: "com.avg_deal", section: "commercial", label: "Average deal size", definition: "Average value of an open opportunity.", unit: "money", higherIsBetter: true, source: "auto", packs: ["growth"] },
  { id: "com.won_value", section: "commercial", label: "Won value", definition: "Total value of opportunities marked won.", unit: "money", higherIsBetter: true, source: "auto", packs: ["growth"] },
  { id: "com.open_count", section: "commercial", label: "Open opportunities", definition: "Number of live opportunities in the funnel.", unit: "num", higherIsBetter: true, source: "auto", packs: [] },
  { id: "com.concentration", section: "commercial", label: "Top-customer share", definition: "Largest customer as a share of open pipeline value.", unit: "pct", higherIsBetter: false, defaultTarget: 30, source: "auto", packs: ["essentials", "growth", "bank"] },
  { id: "com.nps", section: "commercial", label: "Net promoter score", definition: "Customer advocacy score you enter each month.", unit: "num", higherIsBetter: true, defaultTarget: 40, source: "manual", packs: [] },
  { id: "com.complaints", section: "commercial", label: "Customer complaints", definition: "Formal complaints received in the month.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "manual", packs: [] },
  { id: "com.quote_turnaround", section: "commercial", label: "Quote turnaround", definition: "Average days from enquiry to quote issued.", unit: "days", higherIsBetter: false, defaultTarget: 5, source: "manual", packs: [] },

  // ── Operations ───────────────────────────────────────────────────────
  { id: "ops.otd", section: "operations", label: "On-time delivery", definition: "Orders delivered on time to customer request.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["otd", "otif", "on-time-delivery"], kpiMatch: "on.?time", packs: ["essentials", "growth"] },
  { id: "ops.oee", section: "operations", label: "OEE", definition: "Availability × performance × quality on the constraint.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["oee"], kpiMatch: "\\bOEE\\b", packs: ["essentials"] },
  { id: "ops.scrap", section: "operations", label: "Scrap rate", definition: "Scrapped material as a share of production.", unit: "pct", higherIsBetter: false, source: "kpi", kpiKeys: ["scrap-rate", "scrap-percentage-material"], kpiMatch: "scrap", packs: ["essentials"] },
  { id: "ops.attainment", section: "operations", label: "Schedule attainment", definition: "Production completed to plan.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["schedule-attainment", "production-plan-attainment"], kpiMatch: "attainment", packs: ["essentials"] },
  { id: "ops.fpy", section: "operations", label: "First pass yield", definition: "Units right first time with no rework.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["fpy", "first-pass-yield"], kpiMatch: "first.?pass", packs: [] },
  { id: "ops.ppm", section: "operations", label: "Customer defect PPM", definition: "Defective parts per million shipped.", unit: "num", higherIsBetter: false, source: "kpi", kpiKeys: ["customer-ppm", "ppm"], kpiMatch: "ppm", packs: [] },
  { id: "ops.rework", section: "operations", label: "Rework rate", definition: "Units requiring rework as a share of output.", unit: "pct", higherIsBetter: false, source: "kpi", kpiKeys: ["rework-rate"], kpiMatch: "rework", packs: [] },
  { id: "ops.copq", section: "operations", label: "Cost of poor quality", definition: "Scrap, rework, warranty and concession cost.", unit: "money", higherIsBetter: false, source: "kpi", kpiKeys: ["copq", "cost-of-poor-quality"], kpiMatch: "poor quality|copq", packs: [] },
  { id: "ops.downtime", section: "operations", label: "Unplanned downtime", definition: "Lost production time from breakdowns.", unit: "pct", higherIsBetter: false, source: "kpi", kpiKeys: ["unplanned-downtime", "downtime"], kpiMatch: "downtime", packs: [] },
  { id: "ops.mtbf", section: "operations", label: "MTBF", definition: "Mean time between equipment failures.", unit: "num", higherIsBetter: true, source: "kpi", kpiKeys: ["mtbf"], kpiMatch: "mtbf", packs: [] },
  { id: "ops.utilisation", section: "operations", label: "Capacity utilisation", definition: "Load against available capacity.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["capacity-utilisation", "capacity-utilization"], kpiMatch: "utili[sz]ation", packs: ["growth"] },
  { id: "ops.lead_time", section: "operations", label: "Manufacturing lead time", definition: "Order to ship elapsed days.", unit: "days", higherIsBetter: false, source: "kpi", kpiKeys: ["manufacturing-lead-time", "lead-time"], kpiMatch: "lead.?time", packs: [] },
  { id: "ops.supplier_otd", section: "operations", label: "Supplier on-time delivery", definition: "Inbound deliveries received on time.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["supplier-otd", "supplier-on-time-delivery"], kpiMatch: "supplier.*(time|otd)", packs: [] },
  { id: "ops.inventory_accuracy", section: "operations", label: "Inventory accuracy", definition: "Cycle-count accuracy against system stock.", unit: "pct", higherIsBetter: true, source: "kpi", kpiKeys: ["inventory-accuracy"], kpiMatch: "inventory accuracy", packs: [] },
  { id: "ops.energy", section: "operations", label: "Energy per unit", definition: "Energy consumed per unit produced.", unit: "num", higherIsBetter: false, source: "kpi", kpiKeys: ["energy-per-unit", "energy-intensity"], kpiMatch: "energy", packs: [] },

  // ── Working capital ──────────────────────────────────────────────────
  { id: "wc.dso", section: "working_capital", label: "DSO — days sales outstanding", definition: "Receivables divided by average daily revenue.", unit: "days", higherIsBetter: false, defaultTarget: 45, source: "auto", packs: ["essentials", "cash", "bank"] },
  { id: "wc.dio", section: "working_capital", label: "Inventory days", definition: "Inventory divided by average daily cost of goods.", unit: "days", higherIsBetter: false, defaultTarget: 60, source: "auto", packs: ["essentials", "cash"] },
  { id: "wc.dpo", section: "working_capital", label: "DPO — days payable", definition: "Payables divided by average daily cost of goods.", unit: "days", higherIsBetter: true, defaultTarget: 45, source: "auto", packs: ["cash"] },
  { id: "wc.ccc", section: "working_capital", label: "Cash conversion cycle", definition: "DSO plus inventory days less DPO.", unit: "days", higherIsBetter: false, defaultTarget: 60, source: "auto", packs: ["essentials", "cash", "bank"] },
  { id: "wc.ar60", section: "working_capital", label: "Receivables over 60 days", definition: "Aged receivables as a share of the total book.", unit: "pct", higherIsBetter: false, defaultTarget: 10, source: "auto", packs: ["essentials", "cash", "bank"] },
  { id: "wc.ar_total", section: "working_capital", label: "Receivables balance", definition: "Total money owed to you.", unit: "money", higherIsBetter: false, source: "auto", packs: ["cash"] },
  { id: "wc.ap_total", section: "working_capital", label: "Payables balance", definition: "Total money you owe suppliers.", unit: "money", higherIsBetter: true, source: "auto", packs: ["cash"] },
  { id: "wc.inventory", section: "working_capital", label: "Inventory value", definition: "Stock on hand at cost.", unit: "money", higherIsBetter: false, source: "auto", packs: ["cash"] },
  { id: "wc.inventory_turns", section: "working_capital", label: "Inventory turns", definition: "LTM cost of goods divided by inventory.", unit: "x", higherIsBetter: true, defaultTarget: 6, source: "auto", packs: ["cash"] },
  { id: "wc.net_wc", section: "working_capital", label: "Net working capital", definition: "Receivables plus inventory less payables.", unit: "money", higherIsBetter: false, source: "auto", packs: ["cash", "bank"] },
  { id: "wc.wc_pct_revenue", section: "working_capital", label: "Working capital % of revenue", definition: "Net working capital over LTM revenue.", unit: "pct", higherIsBetter: false, defaultTarget: 20, source: "auto", packs: ["bank"] },

  // ── People ───────────────────────────────────────────────────────────
  { id: "ppl.headcount", section: "people", label: "Headcount", definition: "People on the payroll at month end.", unit: "num", higherIsBetter: true, source: "auto", packs: ["essentials"] },
  { id: "ppl.rev_per_head", section: "people", label: "Revenue per employee (LTM)", definition: "Last twelve months revenue divided by headcount.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "ppl.labour_pct", section: "people", label: "Labour cost % of revenue", definition: "Total labour cost over revenue.", unit: "pct", higherIsBetter: false, defaultTarget: 30, source: "auto", packs: ["essentials"] },
  { id: "ppl.overtime", section: "people", label: "Overtime", definition: "Overtime hours as a share of hours worked.", unit: "pct", higherIsBetter: false, defaultTarget: 8, source: "auto", packs: ["essentials"] },
  { id: "ppl.turnover", section: "people", label: "Employee turnover", definition: "Annualised leaver rate.", unit: "pct", higherIsBetter: false, defaultTarget: 10, source: "auto", packs: ["essentials"] },
  { id: "ppl.safety", section: "people", label: "Safety incidents (month)", definition: "Recordable incidents in the month.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: ["essentials"] },
  { id: "ppl.open_roles", section: "people", label: "Open critical roles", definition: "Vacant roles flagged as critical.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: [] },
  { id: "ppl.absence", section: "people", label: "Absence rate", definition: "Unplanned absence as a share of scheduled hours.", unit: "pct", higherIsBetter: false, defaultTarget: 3, source: "kpi", kpiKeys: ["absenteeism", "absence-rate"], kpiMatch: "absen", packs: [] },
  { id: "ppl.training", section: "people", label: "Training compliance", definition: "Required training completed and in date.", unit: "pct", higherIsBetter: true, defaultTarget: 95, source: "kpi", kpiKeys: ["training-compliance", "training-hours"], kpiMatch: "training", packs: [] },
  { id: "ppl.engagement", section: "people", label: "Employee engagement", definition: "Survey score you enter each month or quarter.", unit: "num", higherIsBetter: true, source: "manual", packs: [] },

  // ── Risk ─────────────────────────────────────────────────────────────
  { id: "risk.escalations", section: "risk", label: "Open escalations", definition: "Unclosed escalations from daily management.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: ["essentials"] },
  { id: "risk.overdue", section: "risk", label: "Overdue actions", definition: "Actions past their due date.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: ["essentials"] },
  { id: "risk.certs", section: "risk", label: "Certifications expiring (90d)", definition: "People certifications lapsing in the next ninety days.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: ["essentials"] },
  { id: "risk.initiatives", section: "risk", label: "Initiatives at risk", definition: "Blocked or off-track improvement work.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "auto", packs: ["essentials"] },
  { id: "risk.supplier_concentration", section: "risk", label: "Top-supplier share", definition: "Largest supplier as a share of contracted spend.", unit: "pct", higherIsBetter: false, defaultTarget: 25, source: "manual", packs: [] },
  { id: "risk.covenant_headroom", section: "risk", label: "Covenant headroom", definition: "Percentage headroom against your tightest banking covenant.", unit: "pct", higherIsBetter: true, defaultTarget: 20, source: "manual", packs: ["bank"] },
  { id: "risk.insurance_days", section: "risk", label: "Days to insurance renewal", definition: "Days until the main policy renews.", unit: "days", higherIsBetter: true, source: "manual", packs: [] },
  { id: "risk.audit_findings", section: "risk", label: "Open audit findings", definition: "Quality or regulatory findings still open.", unit: "num", higherIsBetter: false, defaultTarget: 0, source: "manual", packs: [] },

  // ── Shareholder value ────────────────────────────────────────────────
  { id: "shv.ebitda_ltm", section: "shareholder", label: "EBITDA (last 12 months)", definition: "Rolling twelve-month EBITDA.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials", "bank"] },
  { id: "shv.ebitda_margin_ltm", section: "shareholder", label: "EBITDA margin (LTM)", definition: "Rolling twelve-month EBITDA over revenue.", unit: "pct", higherIsBetter: true, source: "auto", packs: ["bank"] },
  { id: "shv.net_debt", section: "shareholder", label: "Net debt", definition: "Total debt less cash on hand.", unit: "money", higherIsBetter: false, source: "auto", packs: ["bank", "cash"] },
  { id: "shv.leverage", section: "shareholder", label: "Net debt / EBITDA", definition: "Leverage on rolling twelve-month EBITDA.", unit: "x", higherIsBetter: false, defaultTarget: 3, source: "auto", packs: ["essentials", "bank"] },
  { id: "shv.ev", section: "shareholder", label: "Indicative enterprise value", definition: "LTM EBITDA multiplied by your chosen multiple.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials"] },
  { id: "shv.equity", section: "shareholder", label: "Indicative equity value", definition: "Enterprise value less net debt.", unit: "money", higherIsBetter: true, source: "auto", packs: ["essentials"] },
  { id: "shv.multiple", section: "shareholder", label: "Valuation multiple", definition: "The EBITDA multiple used for the valuation.", unit: "x", higherIsBetter: true, source: "auto", packs: [] },
];

export const OWNER_METRIC_BY_ID = new Map(OWNER_METRICS.map((m) => [m.id, m]));

/** The metrics shown when a template has no explicit selection. */
export const DEFAULT_OWNER_METRIC_IDS = OWNER_METRICS.filter((m) => m.packs.includes("essentials")).map((m) => m.id);

export function metricsForPack(pack: OwnerPackId): string[] {
  return OWNER_METRICS.filter((m) => m.packs.includes(pack)).map((m) => m.id);
}

/** A metric the company invented itself; stored inside the template config. */
export type OwnerCustomMetric = {
  id: string; // always prefixed "custom."
  section: OwnerSectionId;
  label: string;
  definition?: string;
  unit: TileUnit;
  higherIsBetter: boolean;
  target?: number | null;
};
