import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { STAGE_LABEL, formatMoney, type QuoteStatus } from "@/lib/csar";
import { format } from "date-fns";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a2b25" },
  header: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 2, borderBottomColor: "#2d5c48", paddingBottom: 12, marginBottom: 20 },
  brand: { fontSize: 20, fontWeight: 700, color: "#2d5c48" },
  small: { fontSize: 9, color: "#6b7a72" },
  section: { marginBottom: 14 },
  sectionTitle: { fontSize: 9, textTransform: "uppercase", letterSpacing: 1, color: "#6b7a72", marginBottom: 4 },
  h2: { fontSize: 14, fontWeight: 700, marginBottom: 4 },
  boxRow: { flexDirection: "row", gap: 16, marginBottom: 16 },
  box: { flex: 1, borderWidth: 1, borderColor: "#dcdcd2", borderRadius: 4, padding: 10 },
  amountBox: { marginTop: 4, padding: 14, backgroundColor: "#f4f1e8", borderRadius: 6, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  amountLabel: { fontSize: 10, color: "#6b7a72", textTransform: "uppercase", letterSpacing: 1 },
  amount: { fontSize: 22, fontWeight: 700, color: "#2d5c48" },
  notes: { fontSize: 10, lineHeight: 1.5, color: "#3a4a42" },
  footer: { position: "absolute", bottom: 32, left: 48, right: 48, fontSize: 8, color: "#8a978f", textAlign: "center", borderTopWidth: 1, borderTopColor: "#e5e5db", paddingTop: 8 },
});

interface Props {
  quote: any;
  account: { name: string; address?: string | null };
  contact: { name: string; email?: string | null } | null;
  preparedBy: string;
}

export function QuotePDF({ quote, account, contact, preparedBy }: Props) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brand}>DO.Impact</Text>
            <Text style={styles.small}>Sales quote summary</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={{ fontSize: 12, fontWeight: 700 }}>{quote.number || "Quote"}</Text>
            <Text style={styles.small}>{format(new Date(quote.created_at || Date.now()), "MMMM d, yyyy")}</Text>
            <Text style={styles.small}>Stage: {STAGE_LABEL[quote.status as QuoteStatus] ?? quote.status}</Text>
          </View>
        </View>
        <View style={styles.boxRow}>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Prepared for</Text>
            <Text style={{ fontSize: 12, fontWeight: 700 }}>{account.name}</Text>
            {account.address && <Text style={styles.small}>{account.address}</Text>}
            {contact && (<>
              <Text style={{ marginTop: 6, fontSize: 10 }}>Attn: {contact.name}</Text>
              {contact.email && <Text style={styles.small}>{contact.email}</Text>}
            </>)}
          </View>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Prepared by</Text>
            <Text style={{ fontSize: 12, fontWeight: 700 }}>{preparedBy}</Text>
            {quote.expected_close_date && (<Text style={styles.small}>Expected close: {format(new Date(quote.expected_close_date), "MMM d, yyyy")}</Text>)}
            {quote.delivery_date && (<Text style={styles.small}>Delivery: {format(new Date(quote.delivery_date), "MMM d, yyyy")}</Text>)}
          </View>
        </View>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <Text style={styles.h2}>{quote.title}</Text>
        </View>
        <View style={styles.amountBox}>
          <Text style={styles.amountLabel}>Total</Text>
          <Text style={styles.amount}>{formatMoney(Number(quote.amount || 0), quote.currency)}</Text>
        </View>
        {quote.notes && (
          <View style={[styles.section, { marginTop: 20 }]}>
            <Text style={styles.sectionTitle}>Notes</Text>
            <Text style={styles.notes}>{quote.notes}</Text>
          </View>
        )}
        <Text style={styles.footer}>Generated by DO.Impact — this is a summary quote, not a binding contract.</Text>
      </Page>
    </Document>
  );
}
